/*
 * GENERATED by tools/gevr_gen_rom_manifest.py - do not edit.
 *
 * Where each file lives inside a region-u GoldenEye cartridge, in the same
 * order as file_resource_table so the loader can fill hw_address by index.
 *
 * Offsets and lengths only. No cartridge data is stored here; the player
 * supplies the ROM and these say where to look inside it.
 *
 * Source: n64decomp/007, scripts/filelist.u.csv
 */

#include "gevr_rom_manifest.h"

const struct gevrRomFile g_GevrRomFiles[] = {
	{ 0x00000000,        0, 0 },  /* NULLFILE                      */
	{ 0x00438660,    69104, 0 },  /* BG_SEV_ALL_P                 bg/bg_sev_all_p.seg */
	{ 0x00449450,   331584, 0 },  /* BG_SILO_ALL_P                bg/bg_silo_all_p.seg */
	{ 0x0049A390,   139472, 0 },  /* BG_STAT_ALL_P                bg/bg_stat_all_p.seg */
	{ 0x004BC460,   189312, 0 },  /* BG_AREC_ALL_P                bg/bg_arec_all_p.seg */
	{ 0x004EA7E0,   154352, 0 },  /* BG_ARCH_ALL_P                bg/bg_arch_all_p.seg */
	{ 0x005102D0,   132464, 0 },  /* BG_TRA_ALL_P                 bg/bg_tra_all_p.seg */
	{ 0x00530840,   186816, 0 },  /* BG_DEST_ALL_P                bg/bg_dest_all_p.seg */
	{ 0x0055E200,   109984, 0 },  /* BG_SEVB_ALL_P                bg/bg_sevb_all_p.seg */
	{ 0x00578FA0,   137808, 0 },  /* BG_AZT_ALL_P                 bg/bg_azt_all_p.seg */
	{ 0x0059A9F0,   105520, 0 },  /* BG_PETE_ALL_P                bg/bg_pete_all_p.seg */
	{ 0x005B4620,   182640, 0 },  /* BG_DEPO_ALL_P                bg/bg_depo_all_p.seg */
	{ 0x005E0F90,    38416, 0 },  /* BG_REF_ALL_P                 bg/bg_ref_all_p.seg */
	{ 0x005EA5A0,    87728, 0 },  /* BG_CRYP_ALL_P                bg/bg_cryp_all_p.seg */
	{ 0x005FFC50,   197024, 0 },  /* BG_DAM_ALL_P                 bg/bg_dam_all_p.seg */
	{ 0x0062FDF0,   200576, 0 },  /* BG_ARK_ALL_P                 bg/bg_ark_all_p.seg */
	{ 0x00660D70,    41936, 0 },  /* BG_RUN_ALL_P                 bg/bg_run_all_p.seg */
	{ 0x0066B140,   116176, 0 },  /* BG_SEVX_ALL_P                bg/bg_sevx_all_p.seg */
	{ 0x00687710,    86352, 0 },  /* BG_JUN_ALL_P                 bg/bg_jun_all_p.seg */
	{ 0x0069C860,    18544, 0 },  /* BG_DISH_ALL_P                bg/bg_dish_all_p.seg */
	{ 0x006A10D0,   148720, 0 },  /* BG_CAVE_ALL_P                bg/bg_cave_all_p.seg */
	{ 0x006C55C0,    21808, 0 },  /* BG_CAT_ALL_P                 bg/bg_cat_all_p.seg */
	{ 0x006CAAF0,    66384, 0 },  /* BG_CRAD_ALL_P                bg/bg_crad_all_p.seg */
	{ 0x006DAE40,        0, 0 },  /* BG_SHO_ALL_P                 bg/bg_sho_all_p.seg */
	{ 0x00000000,        0, 0 },  /* BG_ELD_ALL_P                 bg/bg_eld_all_p.seg */
	{ 0x006DAE40,        0, 0 },  /* BG_IMP_ALL_P                 bg/bg_imp_all_p.seg */
	{ 0x006DAE40,        0, 0 },  /* BG_ASH_ALL_P                 bg/bg_ash_all_p.seg */
	{ 0x00000000,        0, 0 },  /* BG_LUE_ALL_P                 bg/bg_lue_all_p.seg */
	{ 0x006DAE40,    40800, 0 },  /* BG_AME_ALL_P                 bg/bg_ame_all_p.seg */
	{ 0x006E4DA0,        0, 0 },  /* BG_RIT_ALL_P                 bg/bg_rit_all_p.seg */
	{ 0x006E4DA0,    28240, 0 },  /* BG_OAT_ALL_P                 bg/bg_oat_all_p.seg */
	{ 0x006EBBF0,        0, 0 },  /* BG_EAR_ALL_P                 bg/bg_ear_all_p.seg */
	{ 0x006EBBF0,        0, 0 },  /* BG_LEE_ALL_P                 bg/bg_lee_all_p.seg */
	{ 0x006EBBF0,        0, 0 },  /* BG_LIP_ALL_P                 bg/bg_lip_all_p.seg */
	{ 0x006EBBF0,     4000, 0 },  /* BG_LEN_ALL_P                 bg/bg_len_all_p.seg */
	{ 0x006ECB90,        0, 0 },  /* BG_WAX_ALL_P                 bg/bg_wax_all_p.seg */
	{ 0x006ECB90,        0, 0 },  /* BG_PAM_ALL_P                 bg/bg_pam_all_p.seg */
	{ 0x006ECB90,     9344, 1 },  /* ARMOURGUARD                  CarmourguardZ */
	{ 0x006EF010,    14064, 1 },  /* BARONSAMEDI                  CbaronsamediZ */
	{ 0x006F2700,     9968, 1 },  /* BLUECAMGUARD                 CbluecamguardZ */
	{ 0x006F4DF0,     7696, 1 },  /* BLUEMAN                      CbluemanZ */
	{ 0x006F6C00,     7872, 1 },  /* BLUEWOMAN                    CbluewomanZ */
	{ 0x006F8AC0,    11280, 1 },  /* BOILERBOND                   CboilerbondZ */
	{ 0x006FB6D0,    13952, 1 },  /* BOILERTREV                   CboilertrevZ */
	{ 0x006FED50,    12576, 1 },  /* BORIS                        CborisZ */
	{ 0x00701E70,     9952, 1 },  /* CAMGUARD                     CcamguardZ */
	{ 0x00704550,     7680, 1 },  /* CARDIMAN                     CcardimanZ */
	{ 0x00706350,     7808, 1 },  /* CHECKMAN                     CcheckmanZ */
	{ 0x007081D0,     9728, 1 },  /* COMMGUARD                    CcommguardZ */
	{ 0x0070A7D0,    11920, 1 },  /* DJBOND                       CdjbondZ */
	{ 0x0070D660,     7968, 1 },  /* FATTECHWOMAN                 CfattechwomanZ */
	{ 0x0070F580,    10016, 1 },  /* GREATGUARD2                  Cgreatguard2Z */
	{ 0x00711CA0,     9856, 1 },  /* GREATGUARD                   CgreatguardZ */
	{ 0x00714320,     9936, 1 },  /* GREYGUARD                    CgreyguardZ */
	{ 0x007169F0,     7616, 1 },  /* GREYMAN                      CgreymanZ */
	{ 0x007187B0,     1488, 1 },  /* HEADALAN                     CheadalanZ */
	{ 0x00718D80,     1392, 1 },  /* HEADB                        CheadbZ */
	{ 0x007192F0,      976, 1 },  /* HEADBALACLAVA                CheadbalaclavaZ */
	{ 0x007196C0,     1696, 1 },  /* HEADBIKE                     CheadbikeZ */
	{ 0x00719D60,     3408, 1 },  /* HEADBROSNAN                  CheadbrosnanZ */
	{ 0x0071AAB0,     2976, 1 },  /* HEADBROSNANBOILER            CheadbrosnanboilerZ */
	{ 0x0071B650,     3712, 1 },  /* HEADBROSNANSNOW              CheadbrosnansnowZ */
	{ 0x0071C4D0,     3456, 1 },  /* HEADBROSNANSUIT              CheadbrosnansuitZ */
	{ 0x0071D250,     3008, 1 },  /* HEADBROSNANTIMBER            CheadbrosnantimberZ */
	{ 0x0071DE10,     1344, 1 },  /* HEADCHRIS                    CheadchrisZ */
	{ 0x0071E350,     1408, 1 },  /* HEADDAVE                     CheaddaveZ */
	{ 0x0071E8D0,     1328, 1 },  /* HEADDES                      CheaddesZ */
	{ 0x0071EE00,     1312, 1 },  /* HEADDUNCAN                   CheadduncanZ */
	{ 0x0071F320,     1408, 1 },  /* HEADDWAYNE                   CheaddwayneZ */
	{ 0x0071F8A0,     1392, 1 },  /* HEADGRAHAM                   CheadgrahamZ */
	{ 0x0071FE10,     1328, 1 },  /* HEADGRANT                    CheadgrantZ */
	{ 0x00720340,     1328, 1 },  /* HEADJIM                      CheadjimZ */
	{ 0x00720870,     1056, 1 },  /* HEADJOE2                     Cheadjoe2Z */
	{ 0x00720C90,     1392, 1 },  /* HEADJOE                      CheadjoeZ */
	{ 0x00721200,     1296, 1 },  /* HEADJOEL                     CheadjoelZ */
	{ 0x00721710,     1376, 1 },  /* HEADKARL                     CheadkarlZ */
	{ 0x00721C70,     1360, 1 },  /* HEADKEN                      CheadkenZ */
	{ 0x007221C0,     1408, 1 },  /* HEADLEE                      CheadleeZ */
	{ 0x00722740,     1008, 1 },  /* HEADMANDY                    CheadmandyZ */
	{ 0x00722B30,     1040, 1 },  /* HEADMARION                   CheadmarionZ */
	{ 0x00722F40,     1328, 1 },  /* HEADMARK                     CheadmarkZ */
	{ 0x00723470,     1376, 1 },  /* HEADMARTIN                   CheadmartinZ */
	{ 0x007239D0,     1376, 1 },  /* HEADMISHKIN                  CheadmishkinZ */
	{ 0x00723F30,     1312, 1 },  /* HEADNEIL                     CheadneilZ */
	{ 0x00724450,     1424, 1 },  /* HEADPETE                     CheadpeteZ */
	{ 0x007249E0,     1296, 1 },  /* HEADROBIN                    CheadrobinZ */
	{ 0x00724EF0,     1024, 1 },  /* HEADSALLY                    CheadsallyZ */
	{ 0x007252F0,     1408, 1 },  /* HEADSCOTT                    CheadscottZ */
	{ 0x00725870,     1504, 1 },  /* HEADSHAUN                    CheadshaunZ */
	{ 0x00725E50,     1360, 1 },  /* HEADSTEVEE                   CheadsteveeZ */
	{ 0x007263A0,     1360, 1 },  /* HEADSTEVEH                   CheadstevehZ */
	{ 0x007268F0,     1168, 1 },  /* HEADVIVIEN                   CheadvivienZ */
	{ 0x00726D80,    11328, 1 },  /* JAWS                         CjawsZ */
	{ 0x007299C0,     8208, 1 },  /* JEANWOMAN                    CjeanwomanZ */
	{ 0x0072B9D0,    11168, 1 },  /* MAYDAY                       CmaydayZ */
	{ 0x0072E570,     8528, 1 },  /* MOONFEMALE                   CmoonfemaleZ */
	{ 0x007306C0,     9712, 1 },  /* MOONGUARD                    CmoonguardZ */
	{ 0x00732CB0,    14528, 1 },  /* NATALYA                      CnatalyaZ */
	{ 0x00736570,     9952, 1 },  /* NAVYGUARD                    CnavyguardZ */
	{ 0x00738C50,    12592, 1 },  /* ODDJOB                       CoddjobZ */
	{ 0x0073BD80,     9808, 1 },  /* OLIVEGUARD                   ColiveguardZ */
	{ 0x0073E3D0,    13360, 1 },  /* ORUMOV                       CorumovZ */
	{ 0x00741800,    12416, 1 },  /* PILOT                        CpilotZ */
	{ 0x00744880,    10032, 1 },  /* REDMAN                       CredmanZ */
	{ 0x00746FB0,     7216, 1 },  /* RUSGUARD                     CrusguardZ */
	{ 0x00748BE0,    13104, 1 },  /* SNOWBOND                     CsnowbondZ */
	{ 0x0074BF10,    11392, 1 },  /* SNOWGUARD                    CsnowguardZ */
	{ 0x0074EB90,    14624, 1 },  /* SPICEBOND                    CspicebondZ */
	{ 0x007524B0,    12832, 1 },  /* SUIT_LF_HAND                 Csuit_lf_handZ */
	{ 0x007556D0,    11664, 1 },  /* SUITBOND                     CsuitbondZ */
	{ 0x00758460,     9904, 1 },  /* TECHMAN                      CtechmanZ */
	{ 0x0075AB10,     8176, 1 },  /* TECHWOMAN                    CtechwomanZ */
	{ 0x0075CB00,    11568, 1 },  /* TIMBERBOND                   CtimberbondZ */
	{ 0x0075F830,    14288, 1 },  /* TREVELYAN                    CtrevelyanZ */
	{ 0x00763000,     9744, 1 },  /* TREVGUARD                    CtrevguardZ */
	{ 0x00765610,    12144, 1 },  /* VALENTIN                     CvalentinZ */
	{ 0x00768580,    14832, 1 },  /* XENIA                        CxeniaZ */
	{ 0x0076BF70,     2576, 1 },  /* AK47                         Gak47Z */
	{ 0x0076C980,      912, 1 },  /* AUDIOTAPE                    GaudiotapeZ */
	{ 0x0076CD10,     6160, 1 },  /* AUTOSHOT                     GautoshotZ */
	{ 0x0076E520,     1536, 1 },  /* BLACKBOX                     GblackboxZ */
	{ 0x0076EB20,      256, 1 },  /* BLUEPRINTS                   GblueprintsZ */
	{ 0x0076EC20,     1936, 1 },  /* BOMBCASE                     GbombcaseZ */
	{ 0x0076F3B0,     1520, 1 },  /* BOMBDEFUSER                  GbombdefuserZ */
	{ 0x0076F9A0,     1936, 1 },  /* BRIEFCASE                    GbriefcaseZ */
	{ 0x00770130,     2416, 1 },  /* BUG                          GbugZ */
	{ 0x00770AA0,      848, 1 },  /* BUGDETECTOR                  GbugdetectorZ */
	{ 0x00770DF0,      848, 1 },  /* BUNGEE                       GbungeeZ */
	{ 0x00771140,     1152, 1 },  /* CAMERA                       GcameraZ */
	{ 0x007715C0,      608, 1 },  /* CARTBLUE                     GcartblueZ */
	{ 0x00771820,      304, 1 },  /* CARTRIDGE                    GcartridgeZ */
	{ 0x00771950,      528, 1 },  /* CARTRIFLE                    GcartrifleZ */
	{ 0x00771B60,      512, 1 },  /* CARTSHELL                    GcartshellZ */
	{ 0x00771D60,      320, 1 },  /* CIRCUITBOARD                 GcircuitboardZ */
	{ 0x00771EA0,      496, 1 },  /* CLIPBOARD                    GclipboardZ */
	{ 0x00772090,      848, 1 },  /* CREDITCARD                   GcreditcardZ */
	{ 0x007723E0,      848, 1 },  /* DARKGLASSES                  GdarkglassesZ */
	{ 0x00772730,      320, 1 },  /* DATATHIEF                    GdatathiefZ */
	{ 0x00772870,      368, 1 },  /* DATTAPE                      GdattapeZ */
	{ 0x007729E0,     1408, 1 },  /* DOORDECODER                  GdoordecoderZ */
	{ 0x00772F60,      848, 1 },  /* DOOREXPLODER                 GdoorexploderZ */
	{ 0x007732B0,      864, 1 },  /* DOSSIERRED                   GdossierredZ */
	{ 0x00773610,      848, 1 },  /* DYNAMITE                     GdynamiteZ */
	{ 0x00773960,      592, 1 },  /* EXPLOSIVEFLOPPY              GexplosivefloppyZ */
	{ 0x00773BB0,      848, 1 },  /* EXPLOSIVEPEN                 GexplosivepenZ */
	{ 0x00773F00,     2032, 1 },  /* EXTINGUISHER                 GextinguisherZ */
	{ 0x007746F0,      848, 1 },  /* FINGERGUN                    GfingergunZ */
	{ 0x00774A40,     5888, 1 },  /* FIST                         GfistZ */
	{ 0x00776140,      848, 1 },  /* FLAREPISTOL                  GflarepistolZ */
	{ 0x00776490,     3232, 1 },  /* FNP90                        Gfnp90Z */
	{ 0x00777130,     2608, 1 },  /* GASKEYRING                   GgaskeyringZ */
	{ 0x00777B60,      848, 1 },  /* GOLDBAR                      GgoldbarZ */
	{ 0x00777EB0,     2480, 1 },  /* GOLDENEYEKEY                 GgoldeneyekeyZ */
	{ 0x00778860,     6112, 1 },  /* GOLDENGUN                    GgoldengunZ */
	{ 0x0077A040,     6496, 1 },  /* GOLDWPPK                     GgoldwppkZ */
	{ 0x0077B9A0,     2608, 1 },  /* GRENADE                      GgrenadeZ */
	{ 0x0077C3D0,     4224, 1 },  /* GRENADELAUNCH                GgrenadelaunchZ */
	{ 0x0077D450,      848, 1 },  /* HEROIN                       GheroinZ */
	{ 0x0077D7A0,     7856, 1 },  /* JOYPAD                       GjoypadZ */
	{ 0x0077F650,     1936, 1 },  /* KEYANALYSERCASE              GkeyanalysercaseZ */
	{ 0x0077FDE0,     2544, 1 },  /* KEYBOLT                      GkeyboltZ */
	{ 0x007807D0,      304, 1 },  /* KEYCARD                      GkeycardZ */
	{ 0x00780900,     3408, 1 },  /* KEYYALE                      GkeyyaleZ */
	{ 0x00781650,     6864, 1 },  /* KNIFE                        GknifeZ */
	{ 0x00783120,     3568, 1 },  /* LASER                        GlaserZ */
	{ 0x00783F10,      848, 1 },  /* LECTRE                       GlectreZ */
	{ 0x00784260,      848, 1 },  /* LOCKEXPLODER                 GlockexploderZ */
	{ 0x007845B0,     2592, 1 },  /* M16                          Gm16Z */
	{ 0x00784FD0,      240, 1 },  /* MAP                          GmapZ */
	{ 0x007850C0,     1600, 1 },  /* MICROCAMERA                  GmicrocameraZ */
	{ 0x00785700,      848, 1 },  /* MICROCODE                    GmicrocodeZ */
	{ 0x00785A50,      848, 1 },  /* MICROFILM                    GmicrofilmZ */
	{ 0x00785DA0,      848, 1 },  /* MONEY                        GmoneyZ */
	{ 0x007860F0,     3040, 1 },  /* MP5K                         Gmp5kZ */
	{ 0x00786CD0,     3328, 1 },  /* MP5KSIL                      Gmp5ksilZ */
	{ 0x007879D0,      848, 1 },  /* PITONGUN                     GpitongunZ */
	{ 0x00787D20,      464, 1 },  /* PLANS                        GplansZ */
	{ 0x00787EF0,      848, 1 },  /* PLASTIQUE                    GplastiqueZ */
	{ 0x00788240,     1376, 1 },  /* POLARIZEDGLASSES             GpolarizedglassesZ */
	{ 0x007887A0,     2032, 1 },  /* PROXIMITYMINE                GproximitymineZ */
	{ 0x00788F90,     2496, 1 },  /* REMOTEMINE                   GremotemineZ */
	{ 0x00789950,     4640, 1 },  /* ROCKETLAUNCH                 GrocketlaunchZ */
	{ 0x0078AB70,     7568, 1 },  /* RUGER                        GrugerZ */
	{ 0x0078C900,     1936, 1 },  /* SAFECRACKERCASE              GsafecrackercaseZ */
	{ 0x0078D090,     3808, 1 },  /* SHOTGUN                      GshotgunZ */
	{ 0x0078DF70,     6496, 1 },  /* SILVERWPPK                   GsilverwppkZ */
	{ 0x0078F8D0,     4608, 1 },  /* SKORPION                     GskorpionZ */
	{ 0x00790AD0,     4208, 1 },  /* SNIPERRIFLE                  GsniperrifleZ */
	{ 0x00791B40,     3200, 1 },  /* SPECTRE                      GspectreZ */
	{ 0x007927C0,      848, 1 },  /* SPOOLTAPE                    GspooltapeZ */
	{ 0x00792B10,      848, 1 },  /* SPYFILE                      GspyfileZ */
	{ 0x00792E60,      416, 1 },  /* STAFFLIST                    GstafflistZ */
	{ 0x00793000,     7776, 1 },  /* TASER                        GtaserZ */
	{ 0x00794E60,     6896, 1 },  /* THROWKNIFE                   GthrowknifeZ */
	{ 0x00796950,     2752, 1 },  /* TIMEDMINE                    GtimedmineZ */
	{ 0x00797410,    13312, 1 },  /* TRIGGER                      GtriggerZ */
	{ 0x0079A810,     6944, 1 },  /* TT33                         Gtt33Z */
	{ 0x0079C330,     2320, 1 },  /* UZI                          GuziZ */
	{ 0x0079CC40,      528, 1 },  /* VIDEOTAPE                    GvideotapeZ */
	{ 0x0079CE50,     5216, 1 },  /* WATCHCOMMUNICATOR            GwatchcommunicatorZ */
	{ 0x0079E2B0,     5216, 1 },  /* WATCHGEIGERCOUNTER           GwatchgeigercounterZ */
	{ 0x0079F710,     5216, 1 },  /* WATCHIDENTIFIER              GwatchidentifierZ */
	{ 0x007A0B70,    13312, 1 },  /* WATCHLASER                   GwatchlaserZ */
	{ 0x007A3F70,     5200, 1 },  /* WATCHMAGNETATTRACT           GwatchmagnetattractZ */
	{ 0x007A53C0,     5216, 1 },  /* WATCHMAGNETREPEL             GwatchmagnetrepelZ */
	{ 0x007A6820,     1936, 1 },  /* WEAPONCASE                   GweaponcaseZ */
	{ 0x007A6FB0,     7312, 1 },  /* WPPK                         GwppkZ */
	{ 0x007A8C40,     7488, 1 },  /* WPPKSIL                      GwppksilZ */
	{ 0x007AA980,      848, 1 },  /* WRISTDART                    GwristdartZ */
	{ 0x007AACD0,     9600, 1 },  /* ICBM                         PICBMZ */
	{ 0x007AD250,     1968, 1 },  /* ICBM_NOSE                    PICBM_noseZ */
	{ 0x007ADA00,      480, 1 },  /* AK47MAG                      Pak47magZ */
	{ 0x007ADBE0,      352, 1 },  /* ALARM1                       Palarm1Z */
	{ 0x007ADD40,      416, 1 },  /* ALARM2                       Palarm2Z */
	{ 0x007ADEE0,      576, 1 },  /* AMMO_CRATE1                  Pammo_crate1Z */
	{ 0x007AE120,      576, 1 },  /* AMMO_CRATE2                  Pammo_crate2Z */
	{ 0x007AE360,      592, 1 },  /* AMMO_CRATE3                  Pammo_crate3Z */
	{ 0x007AE5B0,      624, 1 },  /* AMMO_CRATE4                  Pammo_crate4Z */
	{ 0x007AE820,      704, 1 },  /* AMMO_CRATE5                  Pammo_crate5Z */
	{ 0x007AEAE0,     7264, 1 },  /* APC                          PapcZ */
	{ 0x007B0740,      480, 1 },  /* ARCHSECDOOR1                 Parchsecdoor1Z */
	{ 0x007B0920,      464, 1 },  /* ARCHSECDOOR2                 Parchsecdoor2Z */
	{ 0x007B0AF0,     3584, 1 },  /* ARTIC                        ParticZ */
	{ 0x007B18F0,     2320, 1 },  /* ARTICTRAILER                 PartictrailerZ */
	{ 0x007B2200,      576, 1 },  /* BARRICADE                    PbarricadeZ */
	{ 0x007B2440,      848, 1 },  /* BIN1                         Pbin1Z */
	{ 0x007B2790,      224, 1 },  /* BLOTTER1                     Pblotter1Z */
	{ 0x007B2870,     1184, 1 },  /* BODYARMOUR                   PbodyarmourZ */
	{ 0x007B2D10,     1056, 1 },  /* BODYARMOURVEST               PbodyarmourvestZ */
	{ 0x007B3130,      512, 1 },  /* BOLLARD                      PbollardZ */
	{ 0x007B3330,      368, 1 },  /* BOMB                         PbombZ */
	{ 0x007B34A0,      400, 1 },  /* BOOK1                        Pbook1Z */
	{ 0x007B3630,     1776, 1 },  /* BOOKSHELF1                   Pbookshelf1Z */
	{ 0x007B3D20,      368, 1 },  /* BORG_CRATE                   Pborg_crateZ */
	{ 0x007B3E90,      512, 1 },  /* BOXCARTRIDGES                PboxcartridgesZ */
	{ 0x007B4090,     1072, 1 },  /* BOXES2X4                     Pboxes2x4Z */
	{ 0x007B44C0,     1088, 1 },  /* BOXES3X4                     Pboxes3x4Z */
	{ 0x007B4900,     1632, 1 },  /* BOXES4X4                     Pboxes4x4Z */
	{ 0x007B4F60,      880, 1 },  /* BRAKEUNIT                    PbrakeunitZ */
	{ 0x007B52D0,     1408, 1 },  /* BRIDGE_CONSOLE1A             Pbridge_console1aZ */
	{ 0x007B5850,     1376, 1 },  /* BRIDGE_CONSOLE1B             Pbridge_console1bZ */
	{ 0x007B5DB0,     1408, 1 },  /* BRIDGE_CONSOLE2A             Pbridge_console2aZ */
	{ 0x007B6330,     1264, 1 },  /* BRIDGE_CONSOLE2B             Pbridge_console2bZ */
	{ 0x007B6820,     1360, 1 },  /* BRIDGE_CONSOLE3A             Pbridge_console3aZ */
	{ 0x007B6D70,     1424, 1 },  /* BRIDGE_CONSOLE3B             Pbridge_console3bZ */
	{ 0x007B7300,     3296, 1 },  /* CARBMW                       PcarbmwZ */
	{ 0x007B7FE0,      512, 1 },  /* CARD_BOX1                    Pcard_box1Z */
	{ 0x007B81E0,      576, 1 },  /* CARD_BOX2                    Pcard_box2Z */
	{ 0x007B8420,      496, 1 },  /* CARD_BOX3                    Pcard_box3Z */
	{ 0x007B8610,      432, 1 },  /* CARD_BOX4_LG                 Pcard_box4_lgZ */
	{ 0x007B87C0,      512, 1 },  /* CARD_BOX5_LG                 Pcard_box5_lgZ */
	{ 0x007B89C0,      496, 1 },  /* CARD_BOX6_LG                 Pcard_box6_lgZ */
	{ 0x007B8BB0,     3072, 1 },  /* CARESCORT                    PcarescortZ */
	{ 0x007B97B0,     3120, 1 },  /* CARGOLF                      PcargolfZ */
	{ 0x007BA3E0,     4416, 1 },  /* CARWEIRD                     PcarweirdZ */
	{ 0x007BB520,     5632, 1 },  /* CARZIL                       PcarzilZ */
	{ 0x007BCB20,      896, 1 },  /* CCTV                         PcctvZ */
	{ 0x007BCEA0,     1376, 1 },  /* CHRAUDIOTAPE                 PchraudiotapeZ */
	{ 0x007BD400,      864, 1 },  /* CHRAUTOSHOT                  PchrautoshotZ */
	{ 0x007BD760,     2176, 1 },  /* CHRBLACKBOX                  PchrblackboxZ */
	{ 0x007BDFE0,      336, 1 },  /* CHRBLUEPRINTS                PchrblueprintsZ */
	{ 0x007BE130,      496, 1 },  /* CHRBOMBCASE                  PchrbombcaseZ */
	{ 0x007BE320,     2272, 1 },  /* CHRBOMBDEFUSER               PchrbombdefuserZ */
	{ 0x007BEC00,      400, 1 },  /* CHRBRIEFCASE                 PchrbriefcaseZ */
	{ 0x007BED90,     3504, 1 },  /* CHRBUG                       PchrbugZ */
	{ 0x007BFB40,      368, 1 },  /* CHRBUGDETECTOR               PchrbugdetectorZ */
	{ 0x007BFCB0,      368, 1 },  /* CHRBUNGEE                    PchrbungeeZ */
	{ 0x007BFE20,     1680, 1 },  /* CHRCAMERA                    PchrcameraZ */
	{ 0x007C04B0,      416, 1 },  /* CHRCIRCUITBOARD              PchrcircuitboardZ */
	{ 0x007C0650,      640, 1 },  /* CHRCLIPBOARD                 PchrclipboardZ */
	{ 0x007C08D0,      368, 1 },  /* CHRCREDITCARD                PchrcreditcardZ */
	{ 0x007C0A40,      368, 1 },  /* CHRDARKGLASSES               PchrdarkglassesZ */
	{ 0x007C0BB0,      416, 1 },  /* CHRDATATHIEF                 PchrdatathiefZ */
	{ 0x007C0D50,      496, 1 },  /* CHRDATTAPE                   PchrdattapeZ */
	{ 0x007C0F40,     2144, 1 },  /* CHRDOORDECODER               PchrdoordecoderZ */
	{ 0x007C17A0,      368, 1 },  /* CHRDOOREXPLODER              PchrdoorexploderZ */
	{ 0x007C1910,     1232, 1 },  /* CHRDOSSIERRED                PchrdossierredZ */
	{ 0x007C1DE0,      368, 1 },  /* CHRDYNAMITE                  PchrdynamiteZ */
	{ 0x007C1F50,      368, 1 },  /* CHREXPLOSIVEPEN              PchrexplosivepenZ */
	{ 0x007C20C0,     1280, 1 },  /* CHREXTINGUISHER              PchrextinguisherZ */
	{ 0x007C25C0,      368, 1 },  /* CHRFINGERGUN                 PchrfingergunZ */
	{ 0x007C2730,      368, 1 },  /* CHRFLAREPISTOL               PchrflarepistolZ */
	{ 0x007C28A0,     1120, 1 },  /* CHRFNP90                     Pchrfnp90Z */
	{ 0x007C2D00,     3856, 1 },  /* CHRGASKEYRING                PchrgaskeyringZ */
	{ 0x007C3C10,      368, 1 },  /* CHRGOLDBAR                   PchrgoldbarZ */
	{ 0x007C3D80,      624, 1 },  /* CHRGOLDEN                    PchrgoldenZ */
	{ 0x007C3FF0,     3744, 1 },  /* CHRGOLDENEYEKEY              PchrgoldeneyekeyZ */
	{ 0x007C4E90,      368, 1 },  /* CHRGOLDWPPK                  PchrgoldwppkZ */
	{ 0x007C5000,      880, 1 },  /* CHRGRENADE                   PchrgrenadeZ */
	{ 0x007C5370,      912, 1 },  /* CHRGRENADELAUNCH             PchrgrenadelaunchZ */
	{ 0x007C5700,      624, 1 },  /* CHRGRENADEROUND              PchrgrenaderoundZ */
	{ 0x007C5970,      368, 1 },  /* CHRHEROIN                    PchrheroinZ */
	{ 0x007C5AE0,     1008, 1 },  /* CHRKALASH                    PchrkalashZ */
	{ 0x007C5ED0,      496, 1 },  /* CHRKEYANALYSERCASE           PchrkeyanalysercaseZ */
	{ 0x007C60C0,     3744, 1 },  /* CHRKEYBOLT                   PchrkeyboltZ */
	{ 0x007C6F60,     5216, 1 },  /* CHRKEYYALE                   PchrkeyyaleZ */
	{ 0x007C83C0,      512, 1 },  /* CHRKNIFE                     PchrknifeZ */
	{ 0x007C85C0,      960, 1 },  /* CHRLASER                     PchrlaserZ */
	{ 0x007C8980,      368, 1 },  /* CHRLECTRE                    PchrlectreZ */
	{ 0x007C8AF0,      368, 1 },  /* CHRLOCKEXPLODER              PchrlockexploderZ */
	{ 0x007C8C60,      976, 1 },  /* CHRM16                       Pchrm16Z */
	{ 0x007C9030,      336, 1 },  /* CHRMAP                       PchrmapZ */
	{ 0x007C9180,     2288, 1 },  /* CHRMICROCAMERA               PchrmicrocameraZ */
	{ 0x007C9A70,      368, 1 },  /* CHRMICROCODE                 PchrmicrocodeZ */
	{ 0x007C9BE0,      368, 1 },  /* CHRMICROFILM                 PchrmicrofilmZ */
	{ 0x007C9D50,      368, 1 },  /* CHRMONEY                     PchrmoneyZ */
	{ 0x007C9EC0,      896, 1 },  /* CHRMP5K                      Pchrmp5kZ */
	{ 0x007CA240,     1040, 1 },  /* CHRMP5KSIL                   Pchrmp5ksilZ */
	{ 0x007CA650,      368, 1 },  /* CHRPITONGUN                  PchrpitongunZ */
	{ 0x007CA7C0,      656, 1 },  /* CHRPLANS                     PchrplansZ */
	{ 0x007CAA50,     1120, 1 },  /* CHRPLASTIQUE                 PchrplastiqueZ */
	{ 0x007CAEB0,     2240, 1 },  /* CHRPOLARIZEDGLASSES          PchrpolarizedglassesZ */
	{ 0x007CB770,     1120, 1 },  /* CHRPROXIMITYMINE             PchrproximitymineZ */
	{ 0x007CBBD0,     1120, 1 },  /* CHRREMOTEMINE                PchrremotemineZ */
	{ 0x007CC030,     1456, 1 },  /* CHRROCKET                    PchrrocketZ */
	{ 0x007CC5E0,      992, 1 },  /* CHRROCKETLAUNCH              PchrrocketlaunchZ */
	{ 0x007CC9C0,      992, 1 },  /* CHRRUGER                     PchrrugerZ */
	{ 0x007CCDA0,      496, 1 },  /* CHRSAFECRACKERCASE           PchrsafecrackercaseZ */
	{ 0x007CCF90,      848, 1 },  /* CHRSHOTGUN                   PchrshotgunZ */
	{ 0x007CD2E0,      368, 1 },  /* CHRSILVERWPPK                PchrsilverwppkZ */
	{ 0x007CD450,      896, 1 },  /* CHRSKORPION                  PchrskorpionZ */
	{ 0x007CD7D0,      912, 1 },  /* CHRSNIPERRIFLE               PchrsniperrifleZ */
	{ 0x007CDB60,      880, 1 },  /* CHRSPECTRE                   PchrspectreZ */
	{ 0x007CDED0,      368, 1 },  /* CHRSPOOLTAPE                 PchrspooltapeZ */
	{ 0x007CE040,      368, 1 },  /* CHRSPYFILE                   PchrspyfileZ */
	{ 0x007CE1B0,      544, 1 },  /* CHRSTAFFLIST                 PchrstafflistZ */
	{ 0x007CE3D0,      448, 1 },  /* CHRTESTTUBE                  PchrtesttubeZ */
	{ 0x007CE590,      544, 1 },  /* CHRTHROWKNIFE                PchrthrowknifeZ */
	{ 0x007CE7B0,     1328, 1 },  /* CHRTIMEDMINE                 PchrtimedmineZ */
	{ 0x007CECE0,      656, 1 },  /* CHRTT33                      Pchrtt33Z */
	{ 0x007CEF70,      720, 1 },  /* CHRUZI                       PchruziZ */
	{ 0x007CF240,      720, 1 },  /* CHRVIDEOTAPE                 PchrvideotapeZ */
	{ 0x007CF510,      512, 1 },  /* CHRWEAPONCASE                PchrweaponcaseZ */
	{ 0x007CF710,      576, 1 },  /* CHRWPPK                      PchrwppkZ */
	{ 0x007CF950,      736, 1 },  /* CHRWPPKSIL                   PchrwppksilZ */
	{ 0x007CFC30,      368, 1 },  /* CHRWRISTDART                 PchrwristdartZ */
	{ 0x007CFDA0,     1664, 1 },  /* CONSOLE1                     Pconsole1Z */
	{ 0x007D0420,     1664, 1 },  /* CONSOLE2                     Pconsole2Z */
	{ 0x007D0AA0,     1680, 1 },  /* CONSOLE3                     Pconsole3Z */
	{ 0x007D1130,     1056, 1 },  /* CONSOLE_SEV2A                Pconsole_sev2aZ */
	{ 0x007D1550,     1216, 1 },  /* CONSOLE_SEV2B                Pconsole_sev2bZ */
	{ 0x007D1A10,     1088, 1 },  /* CONSOLE_SEV2C                Pconsole_sev2cZ */
	{ 0x007D1E50,     1072, 1 },  /* CONSOLE_SEV2D                Pconsole_sev2dZ */
	{ 0x007D2280,     1072, 1 },  /* CONSOLE_SEV_GEA              Pconsole_sev_GEaZ */
	{ 0x007D26B0,     1072, 1 },  /* CONSOLE_SEV_GEB              Pconsole_sev_GEbZ */
	{ 0x007D2AE0,     1152, 1 },  /* CONSOLE_SEVA                 Pconsole_sevaZ */
	{ 0x007D2F60,     1136, 1 },  /* CONSOLE_SEVB                 Pconsole_sevbZ */
	{ 0x007D33D0,     1072, 1 },  /* CONSOLE_SEVC                 Pconsole_sevcZ */
	{ 0x007D3800,     1072, 1 },  /* CONSOLE_SEVD                 Pconsole_sevdZ */
	{ 0x007D3C30,      400, 1 },  /* CRYPTDOOR1A                  Pcryptdoor1aZ */
	{ 0x007D3DC0,      400, 1 },  /* CRYPTDOOR1B                  Pcryptdoor1bZ */
	{ 0x007D3F50,      400, 1 },  /* CRYPTDOOR2A                  Pcryptdoor2aZ */
	{ 0x007D40E0,      400, 1 },  /* CRYPTDOOR2B                  Pcryptdoor2bZ */
	{ 0x007D4270,      624, 1 },  /* CRYPTDOOR3                   Pcryptdoor3Z */
	{ 0x007D44E0,      384, 1 },  /* CRYPTDOOR4                   Pcryptdoor4Z */
	{ 0x007D4660,      640, 1 },  /* DAMCHAINDOOR                 PdamchaindoorZ */
	{ 0x007D48E0,      544, 1 },  /* DAMGATEDOOR                  PdamgatedoorZ */
	{ 0x007D4B00,      880, 1 },  /* DAMTUNDOOR                   PdamtundoorZ */
	{ 0x007D4E70,      416, 1 },  /* DEPOT_DOOR_STEEL             Pdepot_door_steelZ */
	{ 0x007D5010,      576, 1 },  /* DEPOT_GATE_ENTRY             Pdepot_gate_entryZ */
	{ 0x007D5250,      384, 1 },  /* DESK1                        Pdesk1Z */
	{ 0x007D53D0,      384, 1 },  /* DESK2                        Pdesk2Z */
	{ 0x007D5550,      576, 1 },  /* DESK_ARECIBO1                Pdesk_arecibo1Z */
	{ 0x007D5790,      768, 1 },  /* DESK_LAMP2                   Pdesk_lamp2Z */
	{ 0x007D5A90,     6384, 1 },  /* DEST_ENGINE                  Pdest_engineZ */
	{ 0x007D7380,     1632, 1 },  /* DEST_EXOCET                  Pdest_exocetZ */
	{ 0x007D79E0,     1648, 1 },  /* DEST_GUN                     Pdest_gunZ */
	{ 0x007D8050,     2208, 1 },  /* DEST_HARPOON                 Pdest_harpoonZ */
	{ 0x007D88F0,     4016, 1 },  /* DEST_SEAWOLF                 Pdest_seawolfZ */
	{ 0x007D98A0,      448, 1 },  /* DISC_READER                  Pdisc_readerZ */
	{ 0x007D9A60,      400, 1 },  /* DISK_DRIVE1                  Pdisk_drive1Z */
	{ 0x007D9BF0,      384, 1 },  /* DOOR_AZT_CHAIR               Pdoor_azt_chairZ */
	{ 0x007D9D70,     1088, 1 },  /* DOOR_AZT_DESK                Pdoor_azt_deskZ */
	{ 0x007DA1B0,      912, 1 },  /* DOOR_AZT_DESK_TOP            Pdoor_azt_desk_topZ */
	{ 0x007DA540,      560, 1 },  /* DOOR_AZTEC                   Pdoor_aztecZ */
	{ 0x007DA770,      768, 1 },  /* DOOR_DEST1                   Pdoor_dest1Z */
	{ 0x007DAA70,      960, 1 },  /* DOOR_DEST2                   Pdoor_dest2Z */
	{ 0x007DAE30,     1376, 1 },  /* DOOR_EYELID                  Pdoor_eyelidZ */
	{ 0x007DB390,     2640, 1 },  /* DOOR_IRIS                    Pdoor_irisZ */
	{ 0x007DBDE0,      752, 1 },  /* DOOR_MF                      Pdoor_mfZ */
	{ 0x007DC0D0,      880, 1 },  /* DOOR_ROLLER1                 Pdoor_roller1Z */
	{ 0x007DC440,      576, 1 },  /* DOOR_ROLLER2                 Pdoor_roller2Z */
	{ 0x007DC680,      576, 1 },  /* DOOR_ROLLER3                 Pdoor_roller3Z */
	{ 0x007DC8C0,      608, 1 },  /* DOOR_ROLLER4                 Pdoor_roller4Z */
	{ 0x007DCB20,      304, 1 },  /* DOOR_ROLLERTRAIN             Pdoor_rollertrainZ */
	{ 0x007DCC50,      608, 1 },  /* DOOR_ST_AREC1                Pdoor_st_arec1Z */
	{ 0x007DCEB0,      736, 1 },  /* DOOR_ST_AREC2                Pdoor_st_arec2Z */
	{ 0x007DD190,      416, 1 },  /* DOOR_WIN                     Pdoor_winZ */
	{ 0x007DD330,     1136, 1 },  /* DOORCONSOLE                  PdoorconsoleZ */
	{ 0x007DD7A0,      880, 1 },  /* DOORPANEL                    PdoorpanelZ */
	{ 0x007DDB10,      336, 1 },  /* DOORPRISON1                  Pdoorprison1Z */
	{ 0x007DDC60,      512, 1 },  /* DOORSTATGATE                 PdoorstatgateZ */
	{ 0x007DDE60,      288, 1 },  /* EXPLOSIONBIT                 PexplosionbitZ */
	{ 0x007DDF80,      384, 1 },  /* FILING_CABINET1              Pfiling_cabinet1Z */
	{ 0x007DE100,      304, 1 },  /* FLAG                         PflagZ */
	{ 0x007DE230,      800, 1 },  /* FLOPPY                       PfloppyZ */
	{ 0x007DE550,      416, 1 },  /* FNP90MAG                     Pfnp90magZ */
	{ 0x007DE6F0,      896, 1 },  /* GAS_PLANT_MET1_DO1           Pgas_plant_met1_do1Z */
	{ 0x007DEA70,      480, 1 },  /* GAS_PLANT_SW2_DO1            Pgas_plant_sw2_do1Z */
	{ 0x007DEC50,      512, 1 },  /* GAS_PLANT_SW3_DO1            Pgas_plant_sw3_do1Z */
	{ 0x007DEE50,      352, 1 },  /* GAS_PLANT_SW4_DO1            Pgas_plant_sw4_do1Z */
	{ 0x007DEFB0,      656, 1 },  /* GAS_PLANT_SW_DO1             Pgas_plant_sw_do1Z */
	{ 0x007DF240,      528, 1 },  /* GAS_PLANT_WC_CUB1            Pgas_plant_wc_cub1Z */
	{ 0x007DF450,      528, 1 },  /* GASBARREL                    PgasbarrelZ */
	{ 0x007DF660,     1344, 1 },  /* GASBARRELS                   PgasbarrelsZ */
	{ 0x007DFBA0,     1376, 1 },  /* GASPLANT_CLEAR_DOOR          Pgasplant_clear_doorZ */
	{ 0x007E0100,     1456, 1 },  /* GASTANK                      PgastankZ */
	{ 0x007E06B0,      352, 1 },  /* GLASSWARE1                   Pglassware1Z */
	{ 0x007E0810,      656, 1 },  /* GLASSWARE2                   Pglassware2Z */
	{ 0x007E0AA0,      528, 1 },  /* GLASSWARE3                   Pglassware3Z */
	{ 0x007E0CB0,     1408, 1 },  /* GLASSWARE4                   Pglassware4Z */
	{ 0x007E1230,     3760, 1 },  /* GOLDENEYELOGO                PgoldeneyelogoZ */
	{ 0x007E20E0,      512, 1 },  /* GOLDENSHELLS                 PgoldenshellsZ */
	{ 0x007E22E0,     2000, 1 },  /* GROUNDGUN                    PgroundgunZ */
	{ 0x007E2AB0,     1856, 1 },  /* GUN_RUNWAY1                  Pgun_runway1Z */
	{ 0x007E31F0,      672, 1 },  /* HATBERET                     PhatberetZ */
	{ 0x007E3490,      720, 1 },  /* HATBERETBLUE                 PhatberetblueZ */
	{ 0x007E3760,      736, 1 },  /* HATBERETRED                  PhatberetredZ */
	{ 0x007E3A40,      208, 1 },  /* HATCHBOLT                    PhatchboltZ */
	{ 0x007E3B10,      544, 1 },  /* HATCHDOOR                    PhatchdoorZ */
	{ 0x007E3D30,      368, 1 },  /* HATCHSEVX                    PhatchsevxZ */
	{ 0x007E3EA0,      560, 1 },  /* HATFURRY                     PhatfurryZ */
	{ 0x007E40D0,      544, 1 },  /* HATFURRYBLACK                PhatfurryblackZ */
	{ 0x007E42F0,      528, 1 },  /* HATFURRYBROWN                PhatfurrybrownZ */
	{ 0x007E4500,      560, 1 },  /* HATHELMET                    PhathelmetZ */
	{ 0x007E4730,      560, 1 },  /* HATHELMETGREY                PhathelmetgreyZ */
	{ 0x007E4960,      992, 1 },  /* HATMOON                      PhatmoonZ */
	{ 0x007E4D40,      784, 1 },  /* HATPEAKED                    PhatpeakedZ */
	{ 0x007E5050,      592, 1 },  /* HATTBIRD                     PhattbirdZ */
	{ 0x007E52A0,      624, 1 },  /* HATTBIRDBROWN                PhattbirdbrownZ */
	{ 0x007E5510,    16928, 1 },  /* HELICOPTER                   PhelicopterZ */
	{ 0x007E9730,     6000, 1 },  /* HIND                         PhindZ */
	{ 0x007EAEA0,     4448, 1 },  /* JEEP                         PjeepZ */
	{ 0x007EC000,      608, 1 },  /* JERRY_CAN1                   Pjerry_can1Z */
	{ 0x007EC260,     1920, 1 },  /* JUNGLE3_TREE                 Pjungle3_treeZ */
	{ 0x007EC9E0,     1328, 1 },  /* JUNGLE5_TREE                 Pjungle5_treeZ */
	{ 0x007ECF10,      848, 1 },  /* KEY_HOLDER                   Pkey_holderZ */
	{ 0x007ED260,      368, 1 },  /* KEYBOARD1                    Pkeyboard1Z */
	{ 0x007ED3D0,      672, 1 },  /* KIT_UNITS1                   Pkit_units1Z */
	{ 0x007ED670,      976, 1 },  /* LABBENCH                     PlabbenchZ */
	{ 0x007EDA40,      624, 1 },  /* LANDMINE                     PlandmineZ */
	{ 0x007EDCB0,     4032, 1 },  /* LEGALPAGE                    PlegalpageZ */
	{ 0x007EEC70,      352, 1 },  /* LETTER_TRAY1                 Pletter_tray1Z */
	{ 0x007EEDD0,      400, 1 },  /* LOCKER3                      Plocker3Z */
	{ 0x007EEF60,      400, 1 },  /* LOCKER4                      Plocker4Z */
	{ 0x007EF0F0,      320, 1 },  /* M16MAG                       Pm16magZ */
	{ 0x007EF230,      512, 1 },  /* MAGNUMSHELLS                 PmagnumshellsZ */
	{ 0x007EF430,      768, 1 },  /* MAINFRAME1                   Pmainframe1Z */
	{ 0x007EF730,      720, 1 },  /* MAINFRAME2                   Pmainframe2Z */
	{ 0x007EFA00,      832, 1 },  /* METAL_CHAIR1                 Pmetal_chair1Z */
	{ 0x007EFD40,      448, 1 },  /* METAL_CRATE1                 Pmetal_crate1Z */
	{ 0x007EFF00,      448, 1 },  /* METAL_CRATE2                 Pmetal_crate2Z */
	{ 0x007F00C0,      448, 1 },  /* METAL_CRATE3                 Pmetal_crate3Z */
	{ 0x007F0280,      448, 1 },  /* METAL_CRATE4                 Pmetal_crate4Z */
	{ 0x007F0440,     6368, 1 },  /* MILCOPTER                    PmilcopterZ */
	{ 0x007F1D20,     8960, 1 },  /* MILTRUCK                     PmiltruckZ */
	{ 0x007F4020,     2576, 1 },  /* MISSILE_RACK2                Pmissile_rack2Z */
	{ 0x007F4A30,      992, 1 },  /* MISSILE_RACK                 Pmissile_rackZ */
	{ 0x007F4E10,      832, 1 },  /* MODEMBOX                     PmodemboxZ */
	{ 0x007F5150,     3776, 1 },  /* MOTORBIKE                    PmotorbikeZ */
	{ 0x007F6010,      336, 1 },  /* MP5KMAG                      Pmp5kmagZ */
	{ 0x007F6160,    10976, 1 },  /* NINTENDOLOGO                 PnintendologoZ */
	{ 0x007F8C40,      624, 1 },  /* OIL_DRUM1                    Poil_drum1Z */
	{ 0x007F8EB0,      752, 1 },  /* OIL_DRUM2                    Poil_drum2Z */
	{ 0x007F91A0,      752, 1 },  /* OIL_DRUM3                    Poil_drum3Z */
	{ 0x007F9490,      752, 1 },  /* OIL_DRUM5                    Poil_drum5Z */
	{ 0x007F9780,      784, 1 },  /* OIL_DRUM6                    Poil_drum6Z */
	{ 0x007F9A90,      768, 1 },  /* OIL_DRUM7                    Poil_drum7Z */
	{ 0x007F9D90,     2640, 1 },  /* PADLOCK                      PpadlockZ */
	{ 0x007FA7E0,     1104, 1 },  /* PALM                         PpalmZ */
	{ 0x007FAC30,     1232, 1 },  /* PALMTREE                     PpalmtreeZ */
	{ 0x007FB100,      320, 1 },  /* PHONE1                       Pphone1Z */
	{ 0x007FB240,     9696, 1 },  /* PLANE                        PplaneZ */
	{ 0x007FD820,      960, 1 },  /* PLANT11                      Pplant11Z */
	{ 0x007FDBE0,      912, 1 },  /* PLANT1                       Pplant1Z */
	{ 0x007FDF70,      864, 1 },  /* PLANT2                       Pplant2Z */
	{ 0x007FE2D0,     1040, 1 },  /* PLANT2B                      Pplant2bZ */
	{ 0x007FE6E0,     1104, 1 },  /* PLANT3                       Pplant3Z */
	{ 0x007FEB30,      432, 1 },  /* RADIO_UNIT1                  Pradio_unit1Z */
	{ 0x007FECE0,      448, 1 },  /* RADIO_UNIT2                  Pradio_unit2Z */
	{ 0x007FEEA0,      448, 1 },  /* RADIO_UNIT3                  Pradio_unit3Z */
	{ 0x007FF060,      448, 1 },  /* RADIO_UNIT4                  Pradio_unit4Z */
	{ 0x007FF220,     1632, 1 },  /* ROOFGUN                      ProofgunZ */
	{ 0x007FF880,      848, 1 },  /* SAFE                         PsafeZ */
	{ 0x007FFBD0,     1264, 1 },  /* SAFEDOOR                     PsafedoorZ */
	{ 0x008000C0,     5488, 1 },  /* SAT1_REFLECT                 Psat1_reflectZ */
	{ 0x00801630,      288, 1 },  /* SATBOX                       PsatboxZ */
	{ 0x00801750,     1120, 1 },  /* SATDISH                      PsatdishZ */
	{ 0x00801BB0,      416, 1 },  /* SEC_PANEL                    Psec_panelZ */
	{ 0x00801D50,      656, 1 },  /* SEV_DOOR3                    Psev_door3Z */
	{ 0x00801FE0,      912, 1 },  /* SEV_DOOR3_WIND               Psev_door3_windZ */
	{ 0x00802370,      992, 1 },  /* SEV_DOOR4_WIND               Psev_door4_windZ */
	{ 0x00802750,      848, 1 },  /* SEV_DOOR                     Psev_doorZ */
	{ 0x00802AA0,      816, 1 },  /* SEV_DOOR_V1                  Psev_door_v1Z */
	{ 0x00802DD0,      944, 1 },  /* SEV_TRISLIDE                 Psev_trislideZ */
	{ 0x00803180,     3872, 1 },  /* SEVDISH                      PsevdishZ */
	{ 0x008040A0,      736, 1 },  /* SEVDOORMETSLIDE              PsevdoormetslideZ */
	{ 0x00804380,      368, 1 },  /* SEVDOORNOWIND                PsevdoornowindZ */
	{ 0x008044F0,     1072, 1 },  /* SEVDOORWIND                  PsevdoorwindZ */
	{ 0x00804920,      944, 1 },  /* SEVDOORWOOD                  PsevdoorwoodZ */
	{ 0x00804CD0,    10752, 1 },  /* SHUTTLE                      PshuttleZ */
	{ 0x008076D0,     3120, 1 },  /* SHUTTLE_DOOR_L               Pshuttle_door_lZ */
	{ 0x00808300,     3328, 1 },  /* SHUTTLE_DOOR_R               Pshuttle_door_rZ */
	{ 0x00809000,      416, 1 },  /* SILENCER                     PsilencerZ */
	{ 0x008091A0,      576, 1 },  /* SILO_LIFT_DOOR               Psilo_lift_doorZ */
	{ 0x008093E0,      752, 1 },  /* SILOTOPDOOR                  PsilotopdoorZ */
	{ 0x008096D0,      352, 1 },  /* SKORPIONMAG                  PskorpionmagZ */
	{ 0x00809830,      368, 1 },  /* SPECTREMAG                   PspectremagZ */
	{ 0x008099A0,     3392, 1 },  /* SPEEDBOAT                    PspeedboatZ */
	{ 0x0080A6E0,    12608, 1 },  /* ST_PETE_ROOM_1I              Pst_pete_room_1iZ */
	{ 0x0080D820,    12768, 1 },  /* ST_PETE_ROOM_2I              Pst_pete_room_2iZ */
	{ 0x00810A00,    12096, 1 },  /* ST_PETE_ROOM_3T              Pst_pete_room_3tZ */
	{ 0x00813940,    13712, 1 },  /* ST_PETE_ROOM_5C              Pst_pete_room_5cZ */
	{ 0x00816ED0,    13328, 1 },  /* ST_PETE_ROOM_6C              Pst_pete_room_6cZ */
	{ 0x0081A2E0,      624, 1 },  /* STEEL_DOOR1                  Psteel_door1Z */
	{ 0x0081A550,      688, 1 },  /* STEEL_DOOR2                  Psteel_door2Z */
	{ 0x0081A800,      720, 1 },  /* STEEL_DOOR2B                 Psteel_door2bZ */
	{ 0x0081AAD0,      720, 1 },  /* STEEL_DOOR3                  Psteel_door3Z */
	{ 0x0081ADA0,      704, 1 },  /* STOOL1                       Pstool1Z */
	{ 0x0081B060,      400, 1 },  /* SWIPE_CARD2                  Pswipe_card2Z */
	{ 0x0081B1F0,      656, 1 },  /* SWIVEL_CHAIR1                Pswivel_chair1Z */
	{ 0x0081B480,     6816, 1 },  /* TANK                         PtankZ */
	{ 0x0081CF20,     7824, 1 },  /* TIGER                        PtigerZ */
	{ 0x0081EDB0,     2176, 1 },  /* TORPEDO_RACK                 Ptorpedo_rackZ */
	{ 0x0081F630,      976, 1 },  /* TRAIN_DOOR2                  Ptrain_door2Z */
	{ 0x0081FA00,     1056, 1 },  /* TRAIN_DOOR3                  Ptrain_door3Z */
	{ 0x0081FE20,      624, 1 },  /* TRAIN_DOOR                   Ptrain_doorZ */
	{ 0x00820090,      832, 1 },  /* TRAINEXTDOOR                 PtrainextdoorZ */
	{ 0x008203D0,      320, 1 },  /* TT33MAG                      Ptt33magZ */
	{ 0x00820510,     1312, 1 },  /* TUNING_CONSOLE1              Ptuning_console1Z */
	{ 0x00820A30,      464, 1 },  /* TV1                          Ptv1Z */
	{ 0x00820C00,      416, 1 },  /* TV4SCREEN                    Ptv4screenZ */
	{ 0x00820DA0,     1744, 1 },  /* TV_HOLDER                    Ptv_holderZ */
	{ 0x00821470,      208, 1 },  /* TVSCREEN                     PtvscreenZ */
	{ 0x00821540,      320, 1 },  /* UZIMAG                       PuzimagZ */
	{ 0x00821680,     1552, 1 },  /* VERTDOOR                     PvertdoorZ */
	{ 0x00821C90,     5552, 1 },  /* WALLETBOND                   PwalletbondZ */
	{ 0x00823240,      240, 1 },  /* WINDOW                       PwindowZ */
	{ 0x00823330,      224, 1 },  /* WINDOW_COR11                 Pwindow_cor11Z */
	{ 0x00823410,      224, 1 },  /* WINDOW_LIB_LG1               Pwindow_lib_lg1Z */
	{ 0x008234F0,      240, 1 },  /* WINDOW_LIB_SM1               Pwindow_lib_sm1Z */
	{ 0x008235E0,      640, 1 },  /* WOOD_LG_CRATE1               Pwood_lg_crate1Z */
	{ 0x00823860,      544, 1 },  /* WOOD_LG_CRATE2               Pwood_lg_crate2Z */
	{ 0x00823A80,      544, 1 },  /* WOOD_MD_CRATE3               Pwood_md_crate3Z */
	{ 0x00823CA0,      608, 1 },  /* WOOD_SM_CRATE4               Pwood_sm_crate4Z */
	{ 0x00823F00,      608, 1 },  /* WOOD_SM_CRATE5               Pwood_sm_crate5Z */
	{ 0x00824160,      544, 1 },  /* WOOD_SM_CRATE6               Pwood_sm_crate6Z */
	{ 0x00824380,      880, 1 },  /* WOODEN_TABLE1                Pwooden_table1Z */
	{ 0x008246F0,      320, 1 },  /* WPPKMAG                      PwppkmagZ */
	{ 0x00824830,     6448, 1 },  /* BG_AME_ALL_P_STAN            Tbg_ame_all_p_stanZ */
	{ 0x00826160,    23792, 1 },  /* BG_ARCH_ALL_P_STAN           Tbg_arch_all_p_stanZ */
	{ 0x0082BE50,    33616, 1 },  /* BG_AREC_ALL_P_STAN           Tbg_arec_all_p_stanZ */
	{ 0x008341A0,    36800, 1 },  /* BG_ARK_ALL_P_STAN            Tbg_ark_all_p_stanZ */
	{ 0x0083D160,     6448, 1 },  /* BG_ASH_ALL_P_STAN            Tbg_ash_all_p_stanZ */
	{ 0x0083EA90,    21888, 1 },  /* BG_AZT_ALL_P_STAN            Tbg_azt_all_p_stanZ */
	{ 0x00844010,    10032, 1 },  /* BG_CAT_ALL_P_STAN            Tbg_cat_all_p_stanZ */
	{ 0x00846740,    20208, 1 },  /* BG_CAVE_ALL_P_STAN           Tbg_cave_all_p_stanZ */
	{ 0x0084B630,    10512, 1 },  /* BG_CRAD_ALL_P_STAN           Tbg_crad_all_p_stanZ */
	{ 0x0084DF40,    12400, 1 },  /* BG_CRYP_ALL_P_STAN           Tbg_cryp_all_p_stanZ */
	{ 0x00850FB0,    41952, 1 },  /* BG_DAM_ALL_P_STAN            Tbg_dam_all_p_stanZ */
	{ 0x0085B390,    28480, 1 },  /* BG_DEPO_ALL_P_STAN           Tbg_depo_all_p_stanZ */
	{ 0x008622D0,    26864, 1 },  /* BG_DEST_ALL_P_STAN           Tbg_dest_all_p_stanZ */
	{ 0x00868BC0,     2832, 1 },  /* BG_DISH_ALL_P_STAN           Tbg_dish_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_EAR_ALL_P_STAN            Tbg_ear_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_ELD_ALL_P_STAN            Tbg_eld_all_p_stanZ */
	{ 0x008696D0,     6448, 1 },  /* BG_IMP_ALL_P_STAN            Tbg_imp_all_p_stanZ */
	{ 0x0086B000,    29008, 1 },  /* BG_JUN_ALL_P_STAN            Tbg_jun_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_LEE_ALL_P_STAN            Tbg_lee_all_p_stanZ */
	{ 0x00872150,     2752, 1 },  /* BG_LEN_ALL_P_STAN            Tbg_len_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_LIP_ALL_P_STAN            Tbg_lip_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_LUE_ALL_P_STAN            Tbg_lue_all_p_stanZ */
	{ 0x00872C10,     6400, 1 },  /* BG_OAT_ALL_P_STAN            Tbg_oat_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_PAM_ALL_P_STAN            Tbg_pam_all_p_stanZ */
	{ 0x00874510,    18064, 1 },  /* BG_PETE_ALL_P_STAN           Tbg_pete_all_p_stanZ */
	{ 0x00878BA0,     7632, 1 },  /* BG_REF_ALL_P_STAN            Tbg_ref_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_RIT_ALL_P_STAN            Tbg_rit_all_p_stanZ */
	{ 0x0087A970,     6784, 1 },  /* BG_RUN_ALL_P_STAN            Tbg_run_all_p_stanZ */
	{ 0x0087C3F0,    15824, 1 },  /* BG_SEV_ALL_P_STAN            Tbg_sev_all_p_stanZ */
	{ 0x008801C0,    20288, 1 },  /* BG_SEVB_ALL_P_STAN           Tbg_sevb_all_p_stanZ */
	{ 0x00885100,    37680, 1 },  /* BG_SEVX_ALL_P_STAN           Tbg_sevx_all_p_stanZ */
	{ 0x0088E430,    37024, 1 },  /* BG_SILO_ALL_P_STAN           Tbg_silo_all_p_stanZ */
	{ 0x008974D0,    20160, 1 },  /* BG_STAT_ALL_P_STAN           Tbg_stat_all_p_stanZ */
	{ 0x0089C390,     9168, 1 },  /* BG_TRA_ALL_P_STAN            Tbg_tra_all_p_stanZ */
	{ 0x00000000,        0, 0 },  /* BG_WAX_ALL_P_STAN            Tbg_wax_all_p_stanZ */
	{ 0x0089E760,       32, 1 },  /* BRIEFARCH                    UbriefarchZ */
	{ 0x0089E780,       32, 1 },  /* BRIEFARK                     UbriefarkZ */
	{ 0x0089E7A0,       32, 1 },  /* BRIEFAZT                     UbriefaztZ */
	{ 0x0089E7C0,       32, 1 },  /* BRIEFCAVE                    UbriefcaveZ */
	{ 0x0089E7E0,       32, 1 },  /* BRIEFCONTROL                 UbriefcontrolZ */
	{ 0x0089E800,       32, 1 },  /* BRIEFCRAD                    UbriefcradZ */
	{ 0x0089E820,       32, 1 },  /* BRIEFCRYP                    UbriefcrypZ */
	{ 0x0089E840,       32, 1 },  /* BRIEFDAM                     UbriefdamZ */
	{ 0x0089E860,       32, 1 },  /* BRIEFDEPO                    UbriefdepoZ */
	{ 0x0089E880,       32, 1 },  /* BRIEFDEST                    UbriefdestZ */
	{ 0x0089E8A0,       32, 1 },  /* BRIEFJUN                     UbriefjunZ */
	{ 0x0089E8C0,       32, 1 },  /* BRIEFPETE                    UbriefpeteZ */
	{ 0x0089E8E0,       32, 1 },  /* BRIEFRUN                     UbriefrunZ */
	{ 0x0089E900,       32, 1 },  /* BRIEFSEVB                    UbriefsevbZ */
	{ 0x0089E920,       32, 1 },  /* BRIEFSEVBUNKER               UbriefsevbunkerZ */
	{ 0x0089E940,       32, 1 },  /* BRIEFSEVX                    UbriefsevxZ */
	{ 0x0089E960,       32, 1 },  /* BRIEFSEVXB                   UbriefsevxbZ */
	{ 0x0089E980,       32, 1 },  /* BRIEFSILO                    UbriefsiloZ */
	{ 0x0089E9A0,       32, 1 },  /* BRIEFSTATUE                  UbriefstatueZ */
	{ 0x0089E9C0,       32, 1 },  /* BRIEFTRA                     UbrieftraZ */
	{ 0x0089E9E0,     1824, 1 },  /* MP_SETUPAME                  Ump_setupameZ */
	{ 0x0089F100,    11680, 1 },  /* MP_SETUPARCH                 Ump_setuparchZ */
	{ 0x008A1EA0,     7488, 1 },  /* MP_SETUPARK                  Ump_setuparkZ */
	{ 0x008A3BE0,     1776, 1 },  /* MP_SETUPASH                  Ump_setupashZ */
	{ 0x008A42D0,     9568, 1 },  /* MP_SETUPCAVE                 Ump_setupcaveZ */
	{ 0x008A6830,     2400, 1 },  /* MP_SETUPCRAD                 Ump_setupcradZ */
	{ 0x008A7190,     3424, 1 },  /* MP_SETUPCRYP                 Ump_setupcrypZ */
	{ 0x008A7EF0,     1008, 1 },  /* MP_SETUPDISH                 Ump_setupdishZ */
	{ 0x008A82E0,     1600, 1 },  /* MP_SETUPIMP                  Ump_setupimpZ */
	{ 0x008A8920,      848, 1 },  /* MP_SETUPOAT                  Ump_setupoatZ */
	{ 0x008A8C70,     1040, 1 },  /* MP_SETUPREF                  Ump_setuprefZ */
	{ 0x008A9080,     4880, 1 },  /* MP_SETUPSEVB                 Ump_setupsevbZ */
	{ 0x008AA390,     3712, 1 },  /* MP_SETUPSTATUE               Ump_setupstatueZ */
	{ 0x008AB210,    17936, 1 },  /* SETUPARCH                    UsetuparchZ */
	{ 0x008AF820,    15248, 1 },  /* SETUPARK                     UsetuparkZ */
	{ 0x008B33B0,    10496, 1 },  /* SETUPAZT                     UsetupaztZ */
	{ 0x008B5CB0,    15968, 1 },  /* SETUPCAVE                    UsetupcaveZ */
	{ 0x008B9B10,    15104, 1 },  /* SETUPCONTROL                 UsetupcontrolZ */
	{ 0x008BD610,     7216, 1 },  /* SETUPCRAD                    UsetupcradZ */
	{ 0x008BF240,     7824, 1 },  /* SETUPCRYP                    UsetupcrypZ */
	{ 0x008C10D0,    17104, 1 },  /* SETUPDAM                     UsetupdamZ */
	{ 0x008C53A0,    12176, 1 },  /* SETUPDEPO                    UsetupdepoZ */
	{ 0x008C8330,     9040, 1 },  /* SETUPDEST                    UsetupdestZ */
	{ 0x008CA680,    14080, 1 },  /* SETUPJUN                     UsetupjunZ */
	{ 0x008CDD80,     1488, 1 },  /* SETUPLEN                     UsetuplenZ */
	{ 0x008CE350,    12160, 1 },  /* SETUPPETE                    UsetuppeteZ */
	{ 0x008D12D0,     6240, 1 },  /* SETUPRUN                     UsetuprunZ */
	{ 0x008D2B30,     9824, 1 },  /* SETUPSEVB                    UsetupsevbZ */
	{ 0x008D5190,     6704, 1 },  /* SETUPSEVBUNKER               UsetupsevbunkerZ */
	{ 0x008D6BC0,    17168, 1 },  /* SETUPSEVX                    UsetupsevxZ */
	{ 0x008DAED0,    16624, 1 },  /* SETUPSEVXB                   UsetupsevxbZ */
	{ 0x008DEFC0,    10832, 1 },  /* SETUPSILO                    UsetupsiloZ */
	{ 0x008E1A10,    10192, 1 },  /* SETUPSTATUE                  UsetupstatueZ */
	{ 0x008E41E0,    12848, 1 },  /* SETUPTRA                     UsetuptraZ */
	{ 0x008E7410,       16, 1 },  /* AMEE                         LameE */
	{ 0x008E7420,       16, 1 },  /* AMEJ                         LameJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* AMEP                         LameP */
#endif
	{ 0x008E7430,     1584, 1 },  /* ARCHE                        LarchE */
	{ 0x008E7A60,     1632, 1 },  /* ARCHJ                        LarchJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* ARCHP                        LarchP */
#endif
	{ 0x008E80C0,     1488, 1 },  /* ARECE                        LarecE */
	{ 0x008E8690,     1424, 1 },  /* ARECJ                        LarecJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* ARECP                        LarecP */
#endif
	{ 0x008E8C20,     1696, 1 },  /* ARKE                         LarkE */
	{ 0x008E92C0,     1712, 1 },  /* ARKJ                         LarkJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* ARKP                         LarkP */
#endif
	{ 0x008E9970,       16, 1 },  /* ASHE                         LashE */
	{ 0x008E9980,       16, 1 },  /* ASHJ                         LashJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* ASHP                         LashP */
#endif
	{ 0x008E9990,     1088, 1 },  /* AZTE                         LaztE */
	{ 0x008E9DD0,     1200, 1 },  /* AZTJ                         LaztJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* AZTP                         LaztP */
#endif
	{ 0x008EA280,       16, 1 },  /* CATE                         LcatE */
	{ 0x008EA290,       16, 1 },  /* CATJ                         LcatJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* CATP                         LcatP */
#endif
	{ 0x008EA2A0,     1024, 1 },  /* CAVEE                        LcaveE */
	{ 0x008EA6A0,     1120, 1 },  /* CAVEJ                        LcaveJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* CAVEP                        LcaveP */
#endif
	{ 0x008EAB00,     1232, 1 },  /* CRADE                        LcradE */
	{ 0x008EAFD0,     1200, 1 },  /* CRADJ                        LcradJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* CRADP                        LcradP */
#endif
	{ 0x008EB480,      592, 1 },  /* CRYPE                        LcrypE */
	{ 0x008EB6D0,      704, 1 },  /* CRYPJ                        LcrypJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* CRYPP                        LcrypP */
#endif
	{ 0x008EB990,     1104, 1 },  /* DAME                         LdamE */
	{ 0x008EBDE0,     1136, 1 },  /* DAMJ                         LdamJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* DAMP                         LdamP */
#endif
	{ 0x008EC250,      880, 1 },  /* DEPOE                        LdepoE */
	{ 0x008EC5C0,      832, 1 },  /* DEPOJ                        LdepoJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* DEPOP                        LdepoP */
#endif
	{ 0x008EC900,     1168, 1 },  /* DESTE                        LdestE */
	{ 0x008ECD90,     1120, 1 },  /* DESTJ                        LdestJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* DESTP                        LdestP */
#endif
	{ 0x008ED1F0,       16, 1 },  /* DISHE                        LdishE */
	{ 0x008ED200,       16, 1 },  /* DISHJ                        LdishJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* DISHP                        LdishP */
#endif
	{ 0x008ED210,       16, 1 },  /* EARE                         LearE */
	{ 0x008ED220,       16, 1 },  /* EARJ                         LearJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* EARP                         LearP */
#endif
	{ 0x008ED230,       16, 1 },  /* ELDE                         LeldE */
	{ 0x008ED240,       16, 1 },  /* ELDJ                         LeldJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* ELDP                         LeldP */
#endif
	{ 0x008ED250,     1824, 1 },  /* GUNE                         LgunE */
	{ 0x008ED970,     1872, 1 },  /* GUNJ                         LgunJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* GUNP                         LgunP */
#endif
	{ 0x008EE0C0,       16, 1 },  /* IMPE                         LimpE */
	{ 0x008EE0D0,       16, 1 },  /* IMPJ                         LimpJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* IMPP                         LimpP */
#endif
	{ 0x008EE0E0,     1312, 1 },  /* JUNE                         LjunE */
	{ 0x008EE600,     1344, 1 },  /* JUNJ                         LjunJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* JUNP                         LjunP */
#endif
	{ 0x008EEB40,       16, 1 },  /* LEEE                         LleeE */
	{ 0x008EEB50,       16, 1 },  /* LEEJ                         LleeJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* LEEP                         LleeP */
#endif
	{ 0x008EEB60,     1600, 1 },  /* LENE                         LlenE */
	{ 0x008EF1A0,      688, 1 },  /* LENJ                         LlenJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* LENP                         LlenP */
#endif
	{ 0x008EF450,       16, 1 },  /* LIPE                         LlipE */
	{ 0x008EF460,       16, 1 },  /* LIPJ                         LlipJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* LIPP                         LlipP */
#endif
	{ 0x008EF470,       16, 1 },  /* LUEE                         LlueE */
	{ 0x008EF480,       16, 1 },  /* LUEJ                         LlueJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* LUEP                         LlueP */
#endif
	{ 0x008EF490,      672, 1 },  /* MISCE                        LmiscE */
	{ 0x008EF730,      736, 1 },  /* MISCJ                        LmiscJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* MISCP                        LmiscP */
#endif
	{ 0x008EFA10,      416, 1 },  /* MPMENUE                      LmpmenuE */
	{ 0x008EFBB0,      400, 1 },  /* MPMENUJ                      LmpmenuJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* MPMENUP                      LmpmenuP */
#endif
	{ 0x008EFD40,      192, 1 },  /* MPWEAPONSE                   LmpweaponsE */
	{ 0x008EFE00,      224, 1 },  /* MPWEAPONSJ                   LmpweaponsJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* MPWEAPONSP                   LmpweaponsP */
#endif
	{ 0x008EFEE0,       16, 1 },  /* OATE                         LoatE */
	{ 0x008EFEF0,       16, 1 },  /* OATJ                         LoatJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* OATP                         LoatP */
#endif
	{ 0x008EFF00,      560, 1 },  /* OPTIONSE                     LoptionsE */
	{ 0x008F0130,      592, 1 },  /* OPTIONSJ                     LoptionsJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* OPTIONSP                     LoptionsP */
#endif
	{ 0x008F0380,       16, 1 },  /* PAME                         LpamE */
	{ 0x008F0390,       16, 1 },  /* PAMJ                         LpamJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* PAMP                         LpamP */
#endif
	{ 0x008F03A0,     1152, 1 },  /* PETEE                        LpeteE */
	{ 0x008F0820,     1136, 1 },  /* PETEJ                        LpeteJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* PETEP                        LpeteP */
#endif
	{ 0x008F0C90,      672, 1 },  /* PROPOBJE                     LpropobjE */
	{ 0x008F0F30,      704, 1 },  /* PROPOBJJ                     LpropobjJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* PROPOBJP                     LpropobjP */
#endif
	{ 0x008F11F0,       16, 1 },  /* REFE                         LrefE */
	{ 0x008F1200,       16, 1 },  /* REFJ                         LrefJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* REFP                         LrefP */
#endif
	{ 0x008F1210,       16, 1 },  /* RITE                         LritE */
	{ 0x008F1220,       16, 1 },  /* RITJ                         LritJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* RITP                         LritP */
#endif
	{ 0x008F1230,      624, 1 },  /* RUNE                         LrunE */
	{ 0x008F14A0,      656, 1 },  /* RUNJ                         LrunJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* RUNP                         LrunP */
#endif
	{ 0x008F1730,     1376, 1 },  /* SEVE                         LsevE */
	{ 0x008F1C90,     1296, 1 },  /* SEVJ                         LsevJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* SEVP                         LsevP */
#endif
	{ 0x008F21A0,     1872, 1 },  /* SEVBE                        LsevbE */
	{ 0x008F28F0,     2032, 1 },  /* SEVBJ                        LsevbJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* SEVBP                        LsevbP */
#endif
	{ 0x008F30E0,     1120, 1 },  /* SEVXE                        LsevxE */
	{ 0x008F3540,      960, 1 },  /* SEVXJ                        LsevxJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* SEVXP                        LsevxP */
#endif
	{ 0x008F3900,     1168, 1 },  /* SEVXBE                       LsevxbE */
	{ 0x008F3D90,     1104, 1 },  /* SEVXBJ                       LsevxbJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* SEVXBP                       LsevxbP */
#endif
	{ 0x008F41E0,       16, 1 },  /* SHOE                         LshoE */
	{ 0x008F41F0,       16, 1 },  /* SHOJ                         LshoJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* SHOP                         LshoP */
#endif
	{ 0x008F4200,     1456, 1 },  /* SILOE                        LsiloE */
	{ 0x008F47B0,     1504, 1 },  /* SILOJ                        LsiloJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* SILOP                        LsiloP */
#endif
	{ 0x008F4D90,     2336, 1 },  /* STATE                        LstatE */
	{ 0x008F56B0,     2160, 1 },  /* STATJ                        LstatJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* STATP                        LstatP */
#endif
	{ 0x008F5F20,     2752, 1 },  /* TITLEE                       LtitleE */
	{ 0x008F69E0,     2960, 1 },  /* TITLEJ                       LtitleJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* TITLEP                       LtitleP */
#endif
	{ 0x008F7570,     1072, 1 },  /* TRAE                         LtraE */
	{ 0x008F79A0,     1056, 1 },  /* TRAJ                         LtraJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* TRAP                         LtraP */
#endif
	{ 0x008F7DC0,       16, 1 },  /* WAXE                         LwaxE */
	{ 0x008F7DD0,       16, 1 },  /* WAXJ                         LwaxJ */
#ifdef VERSION_EU
	{ 0x00000000,        0, 0 },  /* WAXP                         LwaxP */
#endif
	{ 0x00000000,        0, 0 },  /* OBENDSEG                     ob/ob_end.seg */
};

const unsigned int g_GevrRomFileCount =
		sizeof(g_GevrRomFiles) / sizeof(g_GevrRomFiles[0]);

/* Whole segments the engine copies by linker symbol. */
const struct gevrRomFile g_GevrRomSegments[] = {
	{ 0x0028E980,    59360, 0 },  /* GEVR_SEG_ANIMATION_DATA */
	{ 0x00124AC0,  1482432, 0 },  /* GEVR_SEG_ANIMATION_ENTRIES */
	{ 0x0029D160,     2760, 0 },  /* GEVR_SEG_GLOBALIMAGETABLE */
	{ 0x0029E560,    26608, 0 },  /* GEVR_SEG_RAREWARELOGO */
	{ 0x00117880,      192, 0 },  /* GEVR_SEG_FONTDL */
	{ 0x00117940,    46848, 0 },  /* GEVR_SEG_JFONTCHARDATA */
	{ 0x00123040,     6784, 0 },  /* GEVR_SEG_EFONTCHARDATA */
	{ 0x002E63F0,     9392, 0 },  /* GEVR_SEG_FONTBANKGOTHIC */
	{ 0x002E88A0,    13632, 0 },  /* GEVR_SEG_FONTZURICHBOLD */
	{ 0x008F7DF0,  3075872, 0 },  /* GEVR_SEG_IMAGES */
	{ 0x002A4D50,   107904, 0 },  /* GEVR_SEG_GUNBARREL */
};
