/*
 * PORT NOTE - data pointers are filled at runtime, not by the linker.
 *
 * Upstream this column held &<segment>, a symbol the cartridge link supplied.
 * There is no such link here, so each entry carries NULL and the ROM loader
 * fills hw_address during startup. The original symbol name is kept in the
 * comment on each line; it is the key the upstream link map is read by.
 *
 * Regenerate with tools/gevr_make_runtime_file_table.py after refreshing this
 * file from upstream.
 */
//TODO: Autogenerate me
#include "file_resource_id_enums.h"

struct fileentry file_resource_table[] = {
    {NULLFILE, "", 0},
    {BG_SEV_ALL_P, "bg/bg_sev_all_p.seg", NULL} /* bg_sev_all_p_seg */,
    {BG_SILO_ALL_P, "bg/bg_silo_all_p.seg", NULL} /* bg_silo_all_p_seg */,
    {BG_STAT_ALL_P, "bg/bg_stat_all_p.seg", NULL} /* bg_stat_all_p_seg */,
    {BG_AREC_ALL_P, "bg/bg_arec_all_p.seg", NULL} /* bg_arec_all_p_seg */,
    {BG_ARCH_ALL_P, "bg/bg_arch_all_p.seg", NULL} /* bg_arch_all_p_seg */,
    {BG_TRA_ALL_P, "bg/bg_tra_all_p.seg", NULL} /* bg_tra_all_p_seg */,
    {BG_DEST_ALL_P, "bg/bg_dest_all_p.seg", NULL} /* bg_dest_all_p_seg */,
    {BG_SEVB_ALL_P, "bg/bg_sevb_all_p.seg", NULL} /* bg_sevb_all_p_seg */,
    {BG_AZT_ALL_P, "bg/bg_azt_all_p.seg", NULL} /* bg_azt_all_p_seg */,
    {BG_PETE_ALL_P, "bg/bg_pete_all_p.seg", NULL} /* bg_pete_all_p_seg */,
    {BG_DEPO_ALL_P, "bg/bg_depo_all_p.seg", NULL} /* bg_depo_all_p_seg */,
    {BG_REF_ALL_P, "bg/bg_ref_all_p.seg", NULL} /* bg_ref_all_p_seg */,
    {BG_CRYP_ALL_P, "bg/bg_cryp_all_p.seg", NULL} /* bg_cryp_all_p_seg */,
    {BG_DAM_ALL_P, "bg/bg_dam_all_p.seg", NULL} /* bg_dam_all_p_seg */,
    {BG_ARK_ALL_P, "bg/bg_ark_all_p.seg", NULL} /* bg_ark_all_p_seg */,
    {BG_RUN_ALL_P, "bg/bg_run_all_p.seg", NULL} /* bg_run_all_p_seg */,
    {BG_SEVX_ALL_P, "bg/bg_sevx_all_p.seg", NULL} /* bg_sevx_all_p_seg */,
    {BG_JUN_ALL_P, "bg/bg_jun_all_p.seg", NULL} /* bg_jun_all_p_seg */,
    {BG_DISH_ALL_P, "bg/bg_dish_all_p.seg", NULL} /* bg_dish_all_p_seg */,
    {BG_CAVE_ALL_P, "bg/bg_cave_all_p.seg", NULL} /* bg_cave_all_p_seg */,
    {BG_CAT_ALL_P, "bg/bg_cat_all_p.seg", NULL} /* bg_cat_all_p_seg */,
    {BG_CRAD_ALL_P, "bg/bg_crad_all_p.seg", NULL} /* bg_crad_all_p_seg */,
    {BG_SHO_ALL_P, "bg/bg_sho_all_p.seg", NULL} /* bg_sho_all_p_seg */,
    {BG_ELD_ALL_P, "bg/bg_eld_all_p.seg", NULL} /* bg_imp_all_p_seg */,
    {BG_IMP_ALL_P, "bg/bg_imp_all_p.seg", NULL} /* bg_imp_all_p_seg */,
    {BG_ASH_ALL_P, "bg/bg_ash_all_p.seg", NULL} /* bg_imp_all_p_seg */,
    {BG_LUE_ALL_P, "bg/bg_lue_all_p.seg", NULL} /* bg_imp_all_p_seg */,
    {BG_AME_ALL_P, "bg/bg_ame_all_p.seg", NULL} /* bg_imp_all_p_seg */,
    {BG_RIT_ALL_P, "bg/bg_rit_all_p.seg", NULL} /* bg_rit_all_p_seg */,
    {BG_OAT_ALL_P, "bg/bg_oat_all_p.seg", NULL} /* bg_oat_all_p_seg */,
    {BG_EAR_ALL_P, "bg/bg_ear_all_p.seg", NULL} /* bg_ear_all_p_seg */,
    {BG_LEE_ALL_P, "bg/bg_lee_all_p.seg", NULL} /* bg_lee_all_p_seg */,
    {BG_LIP_ALL_P, "bg/bg_lip_all_p.seg", NULL} /* bg_lip_all_p_seg */,
    {BG_LEN_ALL_P, "bg/bg_len_all_p.seg", NULL} /* bg_len_all_p_seg */,
    {BG_WAX_ALL_P, "bg/bg_wax_all_p.seg", NULL} /* bg_wax_all_p_seg */,
    {BG_PAM_ALL_P, "bg/bg_pam_all_p.seg", NULL} /* bg_pam_all_p_seg */,

    {ARMOURGUARD, "CarmourguardZ", NULL} /* CarmourguardZ */,
    {BARONSAMEDI, "CbaronsamediZ", NULL} /* CbaronsamediZ */,
    {BLUECAMGUARD, "CbluecamguardZ", NULL} /* CbluecamguardZ */,
    {BLUEMAN, "CbluemanZ", NULL} /* CbluemanZ */,
    {BLUEWOMAN, "CbluewomanZ", NULL} /* CbluewomanZ */,
    {BOILERBOND, "CboilerbondZ", NULL} /* CboilerbondZ */,
    {BOILERTREV, "CboilertrevZ", NULL} /* CboilertrevZ */,
    {BORIS, "CborisZ", NULL} /* CborisZ */,
    {CAMGUARD, "CcamguardZ", NULL} /* CcamguardZ */,
    {CARDIMAN, "CcardimanZ", NULL} /* CcardimanZ */,
    {CHECKMAN, "CcheckmanZ", NULL} /* CcheckmanZ */,
    {COMMGUARD, "CcommguardZ", NULL} /* CcommguardZ */,
    {DJBOND, "CdjbondZ", NULL} /* CdjbondZ */,
    {FATTECHWOMAN, "CfattechwomanZ", NULL} /* CfattechwomanZ */,
    {GREATGUARD2, "Cgreatguard2Z", NULL} /* Cgreatguard2Z */,
    {GREATGUARD, "CgreatguardZ", NULL} /* CgreatguardZ */,
    {GREYGUARD, "CgreyguardZ", NULL} /* CgreyguardZ */,
    {GREYMAN, "CgreymanZ", NULL} /* CgreymanZ */,
    {HEADALAN, "CheadalanZ", NULL} /* CheadalanZ */,
    {HEADB, "CheadbZ", NULL} /* CheadbZ */,
    {HEADBALACLAVA, "CheadbalaclavaZ", NULL} /* CheadbalaclavaZ */,
    {HEADBIKE, "CheadbikeZ", NULL} /* CheadbikeZ */,
    {HEADBROSNAN, "CheadbrosnanZ", NULL} /* CheadbrosnanZ */,
    {HEADBROSNANBOILER, "CheadbrosnanboilerZ", NULL} /* CheadbrosnanboilerZ */,
    {HEADBROSNANSNOW, "CheadbrosnansnowZ", NULL} /* CheadbrosnansnowZ */,
    {HEADBROSNANSUIT, "CheadbrosnansuitZ", NULL} /* CheadbrosnansuitZ */,
    {HEADBROSNANTIMBER, "CheadbrosnantimberZ", NULL} /* CheadbrosnantimberZ */,
    {HEADCHRIS, "CheadchrisZ", NULL} /* CheadchrisZ */,
    {HEADDAVE, "CheaddaveZ", NULL} /* CheaddaveZ */,
    {HEADDES, "CheaddesZ", NULL} /* CheaddesZ */,
    {HEADDUNCAN, "CheadduncanZ", NULL} /* CheadduncanZ */,
    {HEADDWAYNE, "CheaddwayneZ", NULL} /* CheaddwayneZ */,
    {HEADGRAHAM, "CheadgrahamZ", NULL} /* CheadgrahamZ */,
    {HEADGRANT, "CheadgrantZ", NULL} /* CheadgrantZ */,
    {HEADJIM, "CheadjimZ", NULL} /* CheadjimZ */,
    {HEADJOE2, "Cheadjoe2Z", NULL} /* Cheadjoe2Z */,
    {HEADJOE, "CheadjoeZ", NULL} /* CheadjoeZ */,
    {HEADJOEL, "CheadjoelZ", NULL} /* CheadjoelZ */,
    {HEADKARL, "CheadkarlZ", NULL} /* CheadkarlZ */,
    {HEADKEN, "CheadkenZ", NULL} /* CheadkenZ */,
    {HEADLEE, "CheadleeZ", NULL} /* CheadleeZ */,
    {HEADMANDY, "CheadmandyZ", NULL} /* CheadmandyZ */,
    {HEADMARION, "CheadmarionZ", NULL} /* CheadmarionZ */,
    {HEADMARK, "CheadmarkZ", NULL} /* CheadmarkZ */,
    {HEADMARTIN, "CheadmartinZ", NULL} /* CheadmartinZ */,
    {HEADMISHKIN, "CheadmishkinZ", NULL} /* CheadmishkinZ */,
    {HEADNEIL, "CheadneilZ", NULL} /* CheadneilZ */,
    {HEADPETE, "CheadpeteZ", NULL} /* CheadpeteZ */,
    {HEADROBIN, "CheadrobinZ", NULL} /* CheadrobinZ */,
    {HEADSALLY, "CheadsallyZ", NULL} /* CheadsallyZ */,
    {HEADSCOTT, "CheadscottZ", NULL} /* CheadscottZ */,
    {HEADSHAUN, "CheadshaunZ", NULL} /* CheadshaunZ */,
    {HEADSTEVEE, "CheadsteveeZ", NULL} /* CheadsteveeZ */,
    {HEADSTEVEH, "CheadstevehZ", NULL} /* CheadstevehZ */,
    {HEADVIVIEN, "CheadvivienZ", NULL} /* CheadvivienZ */,
    {JAWS, "CjawsZ", NULL} /* CjawsZ */,
    {JEANWOMAN, "CjeanwomanZ", NULL} /* CjeanwomanZ */,
    {MAYDAY, "CmaydayZ", NULL} /* CmaydayZ */,
    {MOONFEMALE, "CmoonfemaleZ", NULL} /* CmoonfemaleZ */,
    {MOONGUARD, "CmoonguardZ", NULL} /* CmoonguardZ */,
    {NATALYA, "CnatalyaZ", NULL} /* CnatalyaZ */,
    {NAVYGUARD, "CnavyguardZ", NULL} /* CnavyguardZ */,
    {ODDJOB, "CoddjobZ", NULL} /* CoddjobZ */,
    {OLIVEGUARD, "ColiveguardZ", NULL} /* ColiveguardZ */,
    {ORUMOV, "CorumovZ", NULL} /* CorumovZ */,
    {PILOT, "CpilotZ", NULL} /* CpilotZ */,
    {REDMAN, "CredmanZ", NULL} /* CredmanZ */,
    {RUSGUARD, "CrusguardZ", NULL} /* CrusguardZ */,
    {SNOWBOND, "CsnowbondZ", NULL} /* CsnowbondZ */,
    {SNOWGUARD, "CsnowguardZ", NULL} /* CsnowguardZ */,
    {SPICEBOND, "CspicebondZ", NULL} /* CspicebondZ */,
    {SUIT_LF_HAND, "Csuit_lf_handZ", NULL} /* Csuit_lf_handZ */,
    {SUITBOND, "CsuitbondZ", NULL} /* CsuitbondZ */,
    {TECHMAN, "CtechmanZ", NULL} /* CtechmanZ */,
    {TECHWOMAN, "CtechwomanZ", NULL} /* CtechwomanZ */,
    {TIMBERBOND, "CtimberbondZ", NULL} /* CtimberbondZ */,
    {TREVELYAN, "CtrevelyanZ", NULL} /* CtrevelyanZ */,
    {TREVGUARD, "CtrevguardZ", NULL} /* CtrevguardZ */,
    {VALENTIN, "CvalentinZ", NULL} /* CvalentinZ */,
    {XENIA, "CxeniaZ", NULL} /* CxeniaZ */,

    {AK47, "Gak47Z", NULL} /* Gak47Z */,
    {AUDIOTAPE, "GaudiotapeZ", NULL} /* GaudiotapeZ */,
    {AUTOSHOT, "GautoshotZ", NULL} /* GautoshotZ */,
    {BLACKBOX, "GblackboxZ", NULL} /* GblackboxZ */,
    {BLUEPRINTS, "GblueprintsZ", NULL} /* GblueprintsZ */,
    {BOMBCASE, "GbombcaseZ", NULL} /* GbombcaseZ */,
    {BOMBDEFUSER, "GbombdefuserZ", NULL} /* GbombdefuserZ */,
    {BRIEFCASE, "GbriefcaseZ", NULL} /* GbriefcaseZ */,
    {BUG, "GbugZ", NULL} /* GbugZ */,
    {BUGDETECTOR, "GbugdetectorZ", NULL} /* GbugdetectorZ */,
    {BUNGEE, "GbungeeZ", NULL} /* GbungeeZ */,
    {CAMERA, "GcameraZ", NULL} /* GcameraZ */,
    {CARTBLUE, "GcartblueZ", NULL} /* GcartblueZ */,
    {CARTRIDGE, "GcartridgeZ", NULL} /* GcartridgeZ */,
    {CARTRIFLE, "GcartrifleZ", NULL} /* GcartrifleZ */,
    {CARTSHELL, "GcartshellZ", NULL} /* GcartshellZ */,
    {CIRCUITBOARD, "GcircuitboardZ", NULL} /* GcircuitboardZ */,
    {CLIPBOARD, "GclipboardZ", NULL} /* GclipboardZ */,
    {CREDITCARD, "GcreditcardZ", NULL} /* GcreditcardZ */,
    {DARKGLASSES, "GdarkglassesZ", NULL} /* GdarkglassesZ */,
    {DATATHIEF, "GdatathiefZ", NULL} /* GdatathiefZ */,
    {DATTAPE, "GdattapeZ", NULL} /* GdattapeZ */,
    {DOORDECODER, "GdoordecoderZ", NULL} /* GdoordecoderZ */,
    {DOOREXPLODER, "GdoorexploderZ", NULL} /* GdoorexploderZ */,
    {DOSSIERRED, "GdossierredZ", NULL} /* GdossierredZ */,
    {DYNAMITE, "GdynamiteZ", NULL} /* GdynamiteZ */,
    {EXPLOSIVEFLOPPY, "GexplosivefloppyZ", NULL} /* GexplosivefloppyZ */,
    {EXPLOSIVEPEN, "GexplosivepenZ", NULL} /* GexplosivepenZ */,
    {EXTINGUISHER, "GextinguisherZ", NULL} /* GextinguisherZ */,
    {FINGERGUN, "GfingergunZ", NULL} /* GfingergunZ */,
    {FIST, "GfistZ", NULL} /* GfistZ */,
    {FLAREPISTOL, "GflarepistolZ", NULL} /* GflarepistolZ */,
    {FNP90, "Gfnp90Z", NULL} /* Gfnp90Z */,
    {GASKEYRING, "GgaskeyringZ", NULL} /* GgaskeyringZ */,
    {GOLDBAR, "GgoldbarZ", NULL} /* GgoldbarZ */,
    {GOLDENEYEKEY, "GgoldeneyekeyZ", NULL} /* GgoldeneyekeyZ */,
    {GOLDENGUN, "GgoldengunZ", NULL} /* GgoldengunZ */,
    {GOLDWPPK, "GgoldwppkZ", NULL} /* GgoldwppkZ */,
    {GRENADE, "GgrenadeZ", NULL} /* GgrenadeZ */,
    {GRENADELAUNCH, "GgrenadelaunchZ", NULL} /* GgrenadelaunchZ */,
    {HEROIN, "GheroinZ", NULL} /* GheroinZ */,
    {JOYPAD, "GjoypadZ", NULL} /* GjoypadZ */,
    {KEYANALYSERCASE, "GkeyanalysercaseZ", NULL} /* GkeyanalysercaseZ */,
    {KEYBOLT, "GkeyboltZ", NULL} /* GkeyboltZ */,
    {KEYCARD, "GkeycardZ", NULL} /* GkeycardZ */,
    {KEYYALE, "GkeyyaleZ", NULL} /* GkeyyaleZ */,
    {KNIFE, "GknifeZ", NULL} /* GknifeZ */,
    {LASER, "GlaserZ", NULL} /* GlaserZ */,
    {LECTRE, "GlectreZ", NULL} /* GlectreZ */,
    {LOCKEXPLODER, "GlockexploderZ", NULL} /* GlockexploderZ */,
    {M16, "Gm16Z", NULL} /* Gm16Z */,
    {MAP, "GmapZ", NULL} /* GmapZ */,
    {MICROCAMERA, "GmicrocameraZ", NULL} /* GmicrocameraZ */,
    {MICROCODE, "GmicrocodeZ", NULL} /* GmicrocodeZ */,
    {MICROFILM, "GmicrofilmZ", NULL} /* GmicrofilmZ */,
    {MONEY, "GmoneyZ", NULL} /* GmoneyZ */,
    {MP5K, "Gmp5kZ", NULL} /* Gmp5kZ */,
    {MP5KSIL, "Gmp5ksilZ", NULL} /* Gmp5ksilZ */,
    {PITONGUN, "GpitongunZ", NULL} /* GpitongunZ */,
    {PLANS, "GplansZ", NULL} /* GplansZ */,
    {PLASTIQUE, "GplastiqueZ", NULL} /* GplastiqueZ */,
    {POLARIZEDGLASSES, "GpolarizedglassesZ", NULL} /* GpolarizedglassesZ */,
    {PROXIMITYMINE, "GproximitymineZ", NULL} /* GproximitymineZ */,
    {REMOTEMINE, "GremotemineZ", NULL} /* GremotemineZ */,
    {ROCKETLAUNCH, "GrocketlaunchZ", NULL} /* GrocketlaunchZ */,
    {RUGER, "GrugerZ", NULL} /* GrugerZ */,
    {SAFECRACKERCASE, "GsafecrackercaseZ", NULL} /* GsafecrackercaseZ */,
    {SHOTGUN, "GshotgunZ", NULL} /* GshotgunZ */,
    {SILVERWPPK, "GsilverwppkZ", NULL} /* GsilverwppkZ */,
    {SKORPION, "GskorpionZ", NULL} /* GskorpionZ */,
    {SNIPERRIFLE, "GsniperrifleZ", NULL} /* GsniperrifleZ */,
    {SPECTRE, "GspectreZ", NULL} /* GspectreZ */,
    {SPOOLTAPE, "GspooltapeZ", NULL} /* GspooltapeZ */,
    {SPYFILE, "GspyfileZ", NULL} /* GspyfileZ */,
    {STAFFLIST, "GstafflistZ", NULL} /* GstafflistZ */,
    {TASER, "GtaserZ", NULL} /* GtaserZ */,
    {THROWKNIFE, "GthrowknifeZ", NULL} /* GthrowknifeZ */,
    {TIMEDMINE, "GtimedmineZ", NULL} /* GtimedmineZ */,
    {TRIGGER, "GtriggerZ", NULL} /* GtriggerZ */,
    {TT33, "Gtt33Z", NULL} /* Gtt33Z */,
    {UZI, "GuziZ", NULL} /* GuziZ */,
    {VIDEOTAPE, "GvideotapeZ", NULL} /* GvideotapeZ */,
    {WATCHCOMMUNICATOR, "GwatchcommunicatorZ", NULL} /* GwatchcommunicatorZ */,
    {WATCHGEIGERCOUNTER, "GwatchgeigercounterZ", NULL} /* GwatchgeigercounterZ */,
    {WATCHIDENTIFIER, "GwatchidentifierZ", NULL} /* GwatchidentifierZ */,
    {WATCHLASER, "GwatchlaserZ", NULL} /* GwatchlaserZ */,
    {WATCHMAGNETATTRACT, "GwatchmagnetattractZ", NULL} /* GwatchmagnetattractZ */,
    {WATCHMAGNETREPEL, "GwatchmagnetrepelZ", NULL} /* GwatchmagnetrepelZ */,
    {WEAPONCASE, "GweaponcaseZ", NULL} /* GweaponcaseZ */,
    {WPPK, "GwppkZ", NULL} /* GwppkZ */,
    {WPPKSIL, "GwppksilZ", NULL} /* GwppksilZ */,
    {WRISTDART, "GwristdartZ", NULL} /* GwristdartZ */,

    {ICBM, "PICBMZ", NULL} /* PICBMZ */,
    {ICBM_NOSE, "PICBM_noseZ", NULL} /* PICBM_noseZ */,
    {AK47MAG, "Pak47magZ", NULL} /* Pak47magZ */,
    {ALARM1, "Palarm1Z", NULL} /* Palarm1Z */,
    {ALARM2, "Palarm2Z", NULL} /* Palarm2Z */,
    {AMMO_CRATE1, "Pammo_crate1Z", NULL} /* Pammo_crate1Z */,
    {AMMO_CRATE2, "Pammo_crate2Z", NULL} /* Pammo_crate2Z */,
    {AMMO_CRATE3, "Pammo_crate3Z", NULL} /* Pammo_crate3Z */,
    {AMMO_CRATE4, "Pammo_crate4Z", NULL} /* Pammo_crate4Z */,
    {AMMO_CRATE5, "Pammo_crate5Z", NULL} /* Pammo_crate5Z */,
    {APC, "PapcZ", NULL} /* PapcZ */,
    {ARCHSECDOOR1, "Parchsecdoor1Z", NULL} /* Parchsecdoor1Z */,
    {ARCHSECDOOR2, "Parchsecdoor2Z", NULL} /* Parchsecdoor2Z */,
    {ARTIC, "ParticZ", NULL} /* ParticZ */,
    {ARTICTRAILER, "PartictrailerZ", NULL} /* PartictrailerZ */,
    {BARRICADE, "PbarricadeZ", NULL} /* PbarricadeZ */,
    {BIN1, "Pbin1Z", NULL} /* Pbin1Z */,
    {BLOTTER1, "Pblotter1Z", NULL} /* Pblotter1Z */,
    {BODYARMOUR, "PbodyarmourZ", NULL} /* PbodyarmourZ */,
    {BODYARMOURVEST, "PbodyarmourvestZ", NULL} /* PbodyarmourvestZ */,
    {BOLLARD, "PbollardZ", NULL} /* PbollardZ */,
    {BOMB, "PbombZ", NULL} /* PbombZ */,
    {BOOK1, "Pbook1Z", NULL} /* Pbook1Z */,
    {BOOKSHELF1, "Pbookshelf1Z", NULL} /* Pbookshelf1Z */,
    {BORG_CRATE, "Pborg_crateZ", NULL} /* Pborg_crateZ */,
    {BOXCARTRIDGES, "PboxcartridgesZ", NULL} /* PboxcartridgesZ */,
    {BOXES2X4, "Pboxes2x4Z", NULL} /* Pboxes2x4Z */,
    {BOXES3X4, "Pboxes3x4Z", NULL} /* Pboxes3x4Z */,
    {BOXES4X4, "Pboxes4x4Z", NULL} /* Pboxes4x4Z */,
    {BRAKEUNIT, "PbrakeunitZ", NULL} /* PbrakeunitZ */,
    {BRIDGE_CONSOLE1A, "Pbridge_console1aZ", NULL} /* Pbridge_console1aZ */,
    {BRIDGE_CONSOLE1B, "Pbridge_console1bZ", NULL} /* Pbridge_console1bZ */,
    {BRIDGE_CONSOLE2A, "Pbridge_console2aZ", NULL} /* Pbridge_console2aZ */,
    {BRIDGE_CONSOLE2B, "Pbridge_console2bZ", NULL} /* Pbridge_console2bZ */,
    {BRIDGE_CONSOLE3A, "Pbridge_console3aZ", NULL} /* Pbridge_console3aZ */,
    {BRIDGE_CONSOLE3B, "Pbridge_console3bZ", NULL} /* Pbridge_console3bZ */,
    {CARBMW, "PcarbmwZ", NULL} /* PcarbmwZ */,
    {CARD_BOX1, "Pcard_box1Z", NULL} /* Pcard_box1Z */,
    {CARD_BOX2, "Pcard_box2Z", NULL} /* Pcard_box2Z */,
    {CARD_BOX3, "Pcard_box3Z", NULL} /* Pcard_box3Z */,
    {CARD_BOX4_LG, "Pcard_box4_lgZ", NULL} /* Pcard_box4_lgZ */,
    {CARD_BOX5_LG, "Pcard_box5_lgZ", NULL} /* Pcard_box5_lgZ */,
    {CARD_BOX6_LG, "Pcard_box6_lgZ", NULL} /* Pcard_box6_lgZ */,
    {CARESCORT, "PcarescortZ", NULL} /* PcarescortZ */,
    {CARGOLF, "PcargolfZ", NULL} /* PcargolfZ */,
    {CARWEIRD, "PcarweirdZ", NULL} /* PcarweirdZ */,
    {CARZIL, "PcarzilZ", NULL} /* PcarzilZ */,
    {CCTV, "PcctvZ", NULL} /* PcctvZ */,
    {CHRAUDIOTAPE, "PchraudiotapeZ", NULL} /* PchraudiotapeZ */,
    {CHRAUTOSHOT, "PchrautoshotZ", NULL} /* PchrautoshotZ */,
    {CHRBLACKBOX, "PchrblackboxZ", NULL} /* PchrblackboxZ */,
    {CHRBLUEPRINTS, "PchrblueprintsZ", NULL} /* PchrblueprintsZ */,
    {CHRBOMBCASE, "PchrbombcaseZ", NULL} /* PchrbombcaseZ */,
    {CHRBOMBDEFUSER, "PchrbombdefuserZ", NULL} /* PchrbombdefuserZ */,
    {CHRBRIEFCASE, "PchrbriefcaseZ", NULL} /* PchrbriefcaseZ */,
    {CHRBUG, "PchrbugZ", NULL} /* PchrbugZ */,
    {CHRBUGDETECTOR, "PchrbugdetectorZ", NULL} /* PchrbugdetectorZ */,
    {CHRBUNGEE, "PchrbungeeZ", NULL} /* PchrbungeeZ */,
    {CHRCAMERA, "PchrcameraZ", NULL} /* PchrcameraZ */,
    {CHRCIRCUITBOARD, "PchrcircuitboardZ", NULL} /* PchrcircuitboardZ */,
    {CHRCLIPBOARD, "PchrclipboardZ", NULL} /* PchrclipboardZ */,
    {CHRCREDITCARD, "PchrcreditcardZ", NULL} /* PchrcreditcardZ */,
    {CHRDARKGLASSES, "PchrdarkglassesZ", NULL} /* PchrdarkglassesZ */,
    {CHRDATATHIEF, "PchrdatathiefZ", NULL} /* PchrdatathiefZ */,
    {CHRDATTAPE, "PchrdattapeZ", NULL} /* PchrdattapeZ */,
    {CHRDOORDECODER, "PchrdoordecoderZ", NULL} /* PchrdoordecoderZ */,
    {CHRDOOREXPLODER, "PchrdoorexploderZ", NULL} /* PchrdoorexploderZ */,
    {CHRDOSSIERRED, "PchrdossierredZ", NULL} /* PchrdossierredZ */,
    {CHRDYNAMITE, "PchrdynamiteZ", NULL} /* PchrdynamiteZ */,
    {CHREXPLOSIVEPEN, "PchrexplosivepenZ", NULL} /* PchrexplosivepenZ */,
    {CHREXTINGUISHER, "PchrextinguisherZ", NULL} /* PchrextinguisherZ */,
    {CHRFINGERGUN, "PchrfingergunZ", NULL} /* PchrfingergunZ */,
    {CHRFLAREPISTOL, "PchrflarepistolZ", NULL} /* PchrflarepistolZ */,
    {CHRFNP90, "Pchrfnp90Z", NULL} /* Pchrfnp90Z */,
    {CHRGASKEYRING, "PchrgaskeyringZ", NULL} /* PchrgaskeyringZ */,
    {CHRGOLDBAR, "PchrgoldbarZ", NULL} /* PchrgoldbarZ */,
    {CHRGOLDEN, "PchrgoldenZ", NULL} /* PchrgoldenZ */,
    {CHRGOLDENEYEKEY, "PchrgoldeneyekeyZ", NULL} /* PchrgoldeneyekeyZ */,
    {CHRGOLDWPPK, "PchrgoldwppkZ", NULL} /* PchrgoldwppkZ */,
    {CHRGRENADE, "PchrgrenadeZ", NULL} /* PchrgrenadeZ */,
    {CHRGRENADELAUNCH, "PchrgrenadelaunchZ", NULL} /* PchrgrenadelaunchZ */,
    {CHRGRENADEROUND, "PchrgrenaderoundZ", NULL} /* PchrgrenaderoundZ */,
    {CHRHEROIN, "PchrheroinZ", NULL} /* PchrheroinZ */,
    {CHRKALASH, "PchrkalashZ", NULL} /* PchrkalashZ */,
    {CHRKEYANALYSERCASE, "PchrkeyanalysercaseZ", NULL} /* PchrkeyanalysercaseZ */,
    {CHRKEYBOLT, "PchrkeyboltZ", NULL} /* PchrkeyboltZ */,
    {CHRKEYYALE, "PchrkeyyaleZ", NULL} /* PchrkeyyaleZ */,
    {CHRKNIFE, "PchrknifeZ", NULL} /* PchrknifeZ */,
    {CHRLASER, "PchrlaserZ", NULL} /* PchrlaserZ */,
    {CHRLECTRE, "PchrlectreZ", NULL} /* PchrlectreZ */,
    {CHRLOCKEXPLODER, "PchrlockexploderZ", NULL} /* PchrlockexploderZ */,
    {CHRM16, "Pchrm16Z", NULL} /* Pchrm16Z */,
    {CHRMAP, "PchrmapZ", NULL} /* PchrmapZ */,
    {CHRMICROCAMERA, "PchrmicrocameraZ", NULL} /* PchrmicrocameraZ */,
    {CHRMICROCODE, "PchrmicrocodeZ", NULL} /* PchrmicrocodeZ */,
    {CHRMICROFILM, "PchrmicrofilmZ", NULL} /* PchrmicrofilmZ */,
    {CHRMONEY, "PchrmoneyZ", NULL} /* PchrmoneyZ */,
    {CHRMP5K, "Pchrmp5kZ", NULL} /* Pchrmp5kZ */,
    {CHRMP5KSIL, "Pchrmp5ksilZ", NULL} /* Pchrmp5ksilZ */,
    {CHRPITONGUN, "PchrpitongunZ", NULL} /* PchrpitongunZ */,
    {CHRPLANS, "PchrplansZ", NULL} /* PchrplansZ */,
    {CHRPLASTIQUE, "PchrplastiqueZ", NULL} /* PchrplastiqueZ */,
    {CHRPOLARIZEDGLASSES, "PchrpolarizedglassesZ", NULL} /* PchrpolarizedglassesZ */,
    {CHRPROXIMITYMINE, "PchrproximitymineZ", NULL} /* PchrproximitymineZ */,
    {CHRREMOTEMINE, "PchrremotemineZ", NULL} /* PchrremotemineZ */,
    {CHRROCKET, "PchrrocketZ", NULL} /* PchrrocketZ */,
    {CHRROCKETLAUNCH, "PchrrocketlaunchZ", NULL} /* PchrrocketlaunchZ */,
    {CHRRUGER, "PchrrugerZ", NULL} /* PchrrugerZ */,
    {CHRSAFECRACKERCASE, "PchrsafecrackercaseZ", NULL} /* PchrsafecrackercaseZ */,
    {CHRSHOTGUN, "PchrshotgunZ", NULL} /* PchrshotgunZ */,
    {CHRSILVERWPPK, "PchrsilverwppkZ", NULL} /* PchrsilverwppkZ */,
    {CHRSKORPION, "PchrskorpionZ", NULL} /* PchrskorpionZ */,
    {CHRSNIPERRIFLE, "PchrsniperrifleZ", NULL} /* PchrsniperrifleZ */,
    {CHRSPECTRE, "PchrspectreZ", NULL} /* PchrspectreZ */,
    {CHRSPOOLTAPE, "PchrspooltapeZ", NULL} /* PchrspooltapeZ */,
    {CHRSPYFILE, "PchrspyfileZ", NULL} /* PchrspyfileZ */,
    {CHRSTAFFLIST, "PchrstafflistZ", NULL} /* PchrstafflistZ */,
    {CHRTESTTUBE, "PchrtesttubeZ", NULL} /* PchrtesttubeZ */,
    {CHRTHROWKNIFE, "PchrthrowknifeZ", NULL} /* PchrthrowknifeZ */,
    {CHRTIMEDMINE, "PchrtimedmineZ", NULL} /* PchrtimedmineZ */,
    {CHRTT33, "Pchrtt33Z", NULL} /* Pchrtt33Z */,
    {CHRUZI, "PchruziZ", NULL} /* PchruziZ */,
    {CHRVIDEOTAPE, "PchrvideotapeZ", NULL} /* PchrvideotapeZ */,
    {CHRWEAPONCASE, "PchrweaponcaseZ", NULL} /* PchrweaponcaseZ */,
    {CHRWPPK, "PchrwppkZ", NULL} /* PchrwppkZ */,
    {CHRWPPKSIL, "PchrwppksilZ", NULL} /* PchrwppksilZ */,
    {CHRWRISTDART, "PchrwristdartZ", NULL} /* PchrwristdartZ */,
    {CONSOLE1, "Pconsole1Z", NULL} /* Pconsole1Z */,
    {CONSOLE2, "Pconsole2Z", NULL} /* Pconsole2Z */,
    {CONSOLE3, "Pconsole3Z", NULL} /* Pconsole3Z */,
    {CONSOLE_SEV2A, "Pconsole_sev2aZ", NULL} /* Pconsole_sev2aZ */,
    {CONSOLE_SEV2B, "Pconsole_sev2bZ", NULL} /* Pconsole_sev2bZ */,
    {CONSOLE_SEV2C, "Pconsole_sev2cZ", NULL} /* Pconsole_sev2cZ */,
    {CONSOLE_SEV2D, "Pconsole_sev2dZ", NULL} /* Pconsole_sev2dZ */,
    {CONSOLE_SEV_GEA, "Pconsole_sev_GEaZ", NULL} /* Pconsole_sev_GEaZ */,
    {CONSOLE_SEV_GEB, "Pconsole_sev_GEbZ", NULL} /* Pconsole_sev_GEbZ */,
    {CONSOLE_SEVA, "Pconsole_sevaZ", NULL} /* Pconsole_sevaZ */,
    {CONSOLE_SEVB, "Pconsole_sevbZ", NULL} /* Pconsole_sevbZ */,
    {CONSOLE_SEVC, "Pconsole_sevcZ", NULL} /* Pconsole_sevcZ */,
    {CONSOLE_SEVD, "Pconsole_sevdZ", NULL} /* Pconsole_sevdZ */,
    {CRYPTDOOR1A, "Pcryptdoor1aZ", NULL} /* Pcryptdoor1aZ */,
    {CRYPTDOOR1B, "Pcryptdoor1bZ", NULL} /* Pcryptdoor1bZ */,
    {CRYPTDOOR2A, "Pcryptdoor2aZ", NULL} /* Pcryptdoor2aZ */,
    {CRYPTDOOR2B, "Pcryptdoor2bZ", NULL} /* Pcryptdoor2bZ */,
    {CRYPTDOOR3, "Pcryptdoor3Z", NULL} /* Pcryptdoor3Z */,
    {CRYPTDOOR4, "Pcryptdoor4Z", NULL} /* Pcryptdoor4Z */,
    {DAMCHAINDOOR, "PdamchaindoorZ", NULL} /* PdamchaindoorZ */,
    {DAMGATEDOOR, "PdamgatedoorZ", NULL} /* PdamgatedoorZ */,
    {DAMTUNDOOR, "PdamtundoorZ", NULL} /* PdamtundoorZ */,
    {DEPOT_DOOR_STEEL, "Pdepot_door_steelZ", NULL} /* Pdepot_door_steelZ */,
    {DEPOT_GATE_ENTRY, "Pdepot_gate_entryZ", NULL} /* Pdepot_gate_entryZ */,
    {DESK1, "Pdesk1Z", NULL} /* Pdesk1Z */,
    {DESK2, "Pdesk2Z", NULL} /* Pdesk2Z */,
    {DESK_ARECIBO1, "Pdesk_arecibo1Z", NULL} /* Pdesk_arecibo1Z */,
    {DESK_LAMP2, "Pdesk_lamp2Z", NULL} /* Pdesk_lamp2Z */,
    {DEST_ENGINE, "Pdest_engineZ", NULL} /* Pdest_engineZ */,
    {DEST_EXOCET, "Pdest_exocetZ", NULL} /* Pdest_exocetZ */,
    {DEST_GUN, "Pdest_gunZ", NULL} /* Pdest_gunZ */,
    {DEST_HARPOON, "Pdest_harpoonZ", NULL} /* Pdest_harpoonZ */,
    {DEST_SEAWOLF, "Pdest_seawolfZ", NULL} /* Pdest_seawolfZ */,
    {DISC_READER, "Pdisc_readerZ", NULL} /* Pdisc_readerZ */,
    {DISK_DRIVE1, "Pdisk_drive1Z", NULL} /* Pdisk_drive1Z */,
    {DOOR_AZT_CHAIR, "Pdoor_azt_chairZ", NULL} /* Pdoor_azt_chairZ */,
    {DOOR_AZT_DESK, "Pdoor_azt_deskZ", NULL} /* Pdoor_azt_deskZ */,
    {DOOR_AZT_DESK_TOP, "Pdoor_azt_desk_topZ", NULL} /* Pdoor_azt_desk_topZ */,
    {DOOR_AZTEC, "Pdoor_aztecZ", NULL} /* Pdoor_aztecZ */,
    {DOOR_DEST1, "Pdoor_dest1Z", NULL} /* Pdoor_dest1Z */,
    {DOOR_DEST2, "Pdoor_dest2Z", NULL} /* Pdoor_dest2Z */,
    {DOOR_EYELID, "Pdoor_eyelidZ", NULL} /* Pdoor_eyelidZ */,
    {DOOR_IRIS, "Pdoor_irisZ", NULL} /* Pdoor_irisZ */,
    {DOOR_MF, "Pdoor_mfZ", NULL} /* Pdoor_mfZ */,
    {DOOR_ROLLER1, "Pdoor_roller1Z", NULL} /* Pdoor_roller1Z */,
    {DOOR_ROLLER2, "Pdoor_roller2Z", NULL} /* Pdoor_roller2Z */,
    {DOOR_ROLLER3, "Pdoor_roller3Z", NULL} /* Pdoor_roller3Z */,
    {DOOR_ROLLER4, "Pdoor_roller4Z", NULL} /* Pdoor_roller4Z */,
    {DOOR_ROLLERTRAIN, "Pdoor_rollertrainZ", NULL} /* Pdoor_rollertrainZ */,
    {DOOR_ST_AREC1, "Pdoor_st_arec1Z", NULL} /* Pdoor_st_arec1Z */,
    {DOOR_ST_AREC2, "Pdoor_st_arec2Z", NULL} /* Pdoor_st_arec2Z */,
    {DOOR_WIN, "Pdoor_winZ", NULL} /* Pdoor_winZ */,
    {DOORCONSOLE, "PdoorconsoleZ", NULL} /* PdoorconsoleZ */,
    {DOORPANEL, "PdoorpanelZ", NULL} /* PdoorpanelZ */,
    {DOORPRISON1, "Pdoorprison1Z", NULL} /* Pdoorprison1Z */,
    {DOORSTATGATE, "PdoorstatgateZ", NULL} /* PdoorstatgateZ */,
    {EXPLOSIONBIT, "PexplosionbitZ", NULL} /* PexplosionbitZ */,
    {FILING_CABINET1, "Pfiling_cabinet1Z", NULL} /* Pfiling_cabinet1Z */,
    {FLAG, "PflagZ", NULL} /* PflagZ */,
    {FLOPPY, "PfloppyZ", NULL} /* PfloppyZ */,
    {FNP90MAG, "Pfnp90magZ", NULL} /* Pfnp90magZ */,
    {GAS_PLANT_MET1_DO1, "Pgas_plant_met1_do1Z", NULL} /* Pgas_plant_met1_do1Z */,
    {GAS_PLANT_SW2_DO1, "Pgas_plant_sw2_do1Z", NULL} /* Pgas_plant_sw2_do1Z */,
    {GAS_PLANT_SW3_DO1, "Pgas_plant_sw3_do1Z", NULL} /* Pgas_plant_sw3_do1Z */,
    {GAS_PLANT_SW4_DO1, "Pgas_plant_sw4_do1Z", NULL} /* Pgas_plant_sw4_do1Z */,
    {GAS_PLANT_SW_DO1, "Pgas_plant_sw_do1Z", NULL} /* Pgas_plant_sw_do1Z */,
    {GAS_PLANT_WC_CUB1, "Pgas_plant_wc_cub1Z", NULL} /* Pgas_plant_wc_cub1Z */,
    {GASBARREL, "PgasbarrelZ", NULL} /* PgasbarrelZ */,
    {GASBARRELS, "PgasbarrelsZ", NULL} /* PgasbarrelsZ */,
    {GASPLANT_CLEAR_DOOR, "Pgasplant_clear_doorZ", NULL} /* Pgasplant_clear_doorZ */,
    {GASTANK, "PgastankZ", NULL} /* PgastankZ */,
    {GLASSWARE1, "Pglassware1Z", NULL} /* Pglassware1Z */,
    {GLASSWARE2, "Pglassware2Z", NULL} /* Pglassware2Z */,
    {GLASSWARE3, "Pglassware3Z", NULL} /* Pglassware3Z */,
    {GLASSWARE4, "Pglassware4Z", NULL} /* Pglassware4Z */,
    {GOLDENEYELOGO, "PgoldeneyelogoZ", NULL} /* PgoldeneyelogoZ */,
    {GOLDENSHELLS, "PgoldenshellsZ", NULL} /* PgoldenshellsZ */,
    {GROUNDGUN, "PgroundgunZ", NULL} /* PgroundgunZ */,
    {GUN_RUNWAY1, "Pgun_runway1Z", NULL} /* Pgun_runway1Z */,
    {HATBERET, "PhatberetZ", NULL} /* PhatberetZ */,
    {HATBERETBLUE, "PhatberetblueZ", NULL} /* PhatberetblueZ */,
    {HATBERETRED, "PhatberetredZ", NULL} /* PhatberetredZ */,
    {HATCHBOLT, "PhatchboltZ", NULL} /* PhatchboltZ */,
    {HATCHDOOR, "PhatchdoorZ", NULL} /* PhatchdoorZ */,
    {HATCHSEVX, "PhatchsevxZ", NULL} /* PhatchsevxZ */,
    {HATFURRY, "PhatfurryZ", NULL} /* PhatfurryZ */,
    {HATFURRYBLACK, "PhatfurryblackZ", NULL} /* PhatfurryblackZ */,
    {HATFURRYBROWN, "PhatfurrybrownZ", NULL} /* PhatfurrybrownZ */,
    {HATHELMET, "PhathelmetZ", NULL} /* PhathelmetZ */,
    {HATHELMETGREY, "PhathelmetgreyZ", NULL} /* PhathelmetgreyZ */,
    {HATMOON, "PhatmoonZ", NULL} /* PhatmoonZ */,
    {HATPEAKED, "PhatpeakedZ", NULL} /* PhatpeakedZ */,
    {HATTBIRD, "PhattbirdZ", NULL} /* PhattbirdZ */,
    {HATTBIRDBROWN, "PhattbirdbrownZ", NULL} /* PhattbirdbrownZ */,
    {HELICOPTER, "PhelicopterZ", NULL} /* PhelicopterZ */,
    {HIND, "PhindZ", NULL} /* PhindZ */,
    {JEEP, "PjeepZ", NULL} /* PjeepZ */,
    {JERRY_CAN1, "Pjerry_can1Z", NULL} /* Pjerry_can1Z */,
    {JUNGLE3_TREE, "Pjungle3_treeZ", NULL} /* Pjungle3_treeZ */,
    {JUNGLE5_TREE, "Pjungle5_treeZ", NULL} /* Pjungle5_treeZ */,
    {KEY_HOLDER, "Pkey_holderZ", NULL} /* Pkey_holderZ */,
    {KEYBOARD1, "Pkeyboard1Z", NULL} /* Pkeyboard1Z */,
    {KIT_UNITS1, "Pkit_units1Z", NULL} /* Pkit_units1Z */,
    {LABBENCH, "PlabbenchZ", NULL} /* PlabbenchZ */,
    {LANDMINE, "PlandmineZ", NULL} /* PlandmineZ */,
    {LEGALPAGE, "PlegalpageZ", NULL} /* PlegalpageZ */,
    {LETTER_TRAY1, "Pletter_tray1Z", NULL} /* Pletter_tray1Z */,
    {LOCKER3, "Plocker3Z", NULL} /* Plocker3Z */,
    {LOCKER4, "Plocker4Z", NULL} /* Plocker4Z */,
    {M16MAG, "Pm16magZ", NULL} /* Pm16magZ */,
    {MAGNUMSHELLS, "PmagnumshellsZ", NULL} /* PmagnumshellsZ */,
    {MAINFRAME1, "Pmainframe1Z", NULL} /* Pmainframe1Z */,
    {MAINFRAME2, "Pmainframe2Z", NULL} /* Pmainframe2Z */,
    {METAL_CHAIR1, "Pmetal_chair1Z", NULL} /* Pmetal_chair1Z */,
    {METAL_CRATE1, "Pmetal_crate1Z", NULL} /* Pmetal_crate1Z */,
    {METAL_CRATE2, "Pmetal_crate2Z", NULL} /* Pmetal_crate2Z */,
    {METAL_CRATE3, "Pmetal_crate3Z", NULL} /* Pmetal_crate3Z */,
    {METAL_CRATE4, "Pmetal_crate4Z", NULL} /* Pmetal_crate4Z */,
    {MILCOPTER, "PmilcopterZ", NULL} /* PmilcopterZ */,
    {MILTRUCK, "PmiltruckZ", NULL} /* PmiltruckZ */,
    {MISSILE_RACK2, "Pmissile_rack2Z", NULL} /* Pmissile_rack2Z */,
    {MISSILE_RACK, "Pmissile_rackZ", NULL} /* Pmissile_rackZ */,
    {MODEMBOX, "PmodemboxZ", NULL} /* PmodemboxZ */,
    {MOTORBIKE, "PmotorbikeZ", NULL} /* PmotorbikeZ */,
    {MP5KMAG, "Pmp5kmagZ", NULL} /* Pmp5kmagZ */,
    {NINTENDOLOGO, "PnintendologoZ", NULL} /* PnintendologoZ */,
    {OIL_DRUM1, "Poil_drum1Z", NULL} /* Poil_drum1Z */,
    {OIL_DRUM2, "Poil_drum2Z", NULL} /* Poil_drum2Z */,
    {OIL_DRUM3, "Poil_drum3Z", NULL} /* Poil_drum3Z */,
    {OIL_DRUM5, "Poil_drum5Z", NULL} /* Poil_drum5Z */,
    {OIL_DRUM6, "Poil_drum6Z", NULL} /* Poil_drum6Z */,
    {OIL_DRUM7, "Poil_drum7Z", NULL} /* Poil_drum7Z */,
    {PADLOCK, "PpadlockZ", NULL} /* PpadlockZ */,
    {PALM, "PpalmZ", NULL} /* PpalmZ */,
    {PALMTREE, "PpalmtreeZ", NULL} /* PpalmtreeZ */,
    {PHONE1, "Pphone1Z", NULL} /* Pphone1Z */,
    {PLANE, "PplaneZ", NULL} /* PplaneZ */,
    {PLANT11, "Pplant11Z", NULL} /* Pplant11Z */,
    {PLANT1, "Pplant1Z", NULL} /* Pplant1Z */,
    {PLANT2, "Pplant2Z", NULL} /* Pplant2Z */,
    {PLANT2B, "Pplant2bZ", NULL} /* Pplant2bZ */,
    {PLANT3, "Pplant3Z", NULL} /* Pplant3Z */,
    {RADIO_UNIT1, "Pradio_unit1Z", NULL} /* Pradio_unit1Z */,
    {RADIO_UNIT2, "Pradio_unit2Z", NULL} /* Pradio_unit2Z */,
    {RADIO_UNIT3, "Pradio_unit3Z", NULL} /* Pradio_unit3Z */,
    {RADIO_UNIT4, "Pradio_unit4Z", NULL} /* Pradio_unit4Z */,
    {ROOFGUN, "ProofgunZ", NULL} /* ProofgunZ */,
    {SAFE, "PsafeZ", NULL} /* PsafeZ */,
    {SAFEDOOR, "PsafedoorZ", NULL} /* PsafedoorZ */,
    {SAT1_REFLECT, "Psat1_reflectZ", NULL} /* Psat1_reflectZ */,
    {SATBOX, "PsatboxZ", NULL} /* PsatboxZ */,
    {SATDISH, "PsatdishZ", NULL} /* PsatdishZ */,
    {SEC_PANEL, "Psec_panelZ", NULL} /* Psec_panelZ */,
    {SEV_DOOR3, "Psev_door3Z", NULL} /* Psev_door3Z */,
    {SEV_DOOR3_WIND, "Psev_door3_windZ", NULL} /* Psev_door3_windZ */,
    {SEV_DOOR4_WIND, "Psev_door4_windZ", NULL} /* Psev_door4_windZ */,
    {SEV_DOOR, "Psev_doorZ", NULL} /* Psev_doorZ */,
    {SEV_DOOR_V1, "Psev_door_v1Z", NULL} /* Psev_door_v1Z */,
    {SEV_TRISLIDE, "Psev_trislideZ", NULL} /* Psev_trislideZ */,
    {SEVDISH, "PsevdishZ", NULL} /* PsevdishZ */,
    {SEVDOORMETSLIDE, "PsevdoormetslideZ", NULL} /* PsevdoormetslideZ */,
    {SEVDOORNOWIND, "PsevdoornowindZ", NULL} /* PsevdoornowindZ */,
    {SEVDOORWIND, "PsevdoorwindZ", NULL} /* PsevdoorwindZ */,
    {SEVDOORWOOD, "PsevdoorwoodZ", NULL} /* PsevdoorwoodZ */,
    {SHUTTLE, "PshuttleZ", NULL} /* PshuttleZ */,
    {SHUTTLE_DOOR_L, "Pshuttle_door_lZ", NULL} /* Pshuttle_door_lZ */,
    {SHUTTLE_DOOR_R, "Pshuttle_door_rZ", NULL} /* Pshuttle_door_rZ */,
    {SILENCER, "PsilencerZ", NULL} /* PsilencerZ */,
    {SILO_LIFT_DOOR, "Psilo_lift_doorZ", NULL} /* Psilo_lift_doorZ */,
    {SILOTOPDOOR, "PsilotopdoorZ", NULL} /* PsilotopdoorZ */,
    {SKORPIONMAG, "PskorpionmagZ", NULL} /* PskorpionmagZ */,
    {SPECTREMAG, "PspectremagZ", NULL} /* PspectremagZ */,
    {SPEEDBOAT, "PspeedboatZ", NULL} /* PspeedboatZ */,
    {ST_PETE_ROOM_1I, "Pst_pete_room_1iZ", NULL} /* Pst_pete_room_1iZ */,
    {ST_PETE_ROOM_2I, "Pst_pete_room_2iZ", NULL} /* Pst_pete_room_2iZ */,
    {ST_PETE_ROOM_3T, "Pst_pete_room_3tZ", NULL} /* Pst_pete_room_3tZ */,
    {ST_PETE_ROOM_5C, "Pst_pete_room_5cZ", NULL} /* Pst_pete_room_5cZ */,
    {ST_PETE_ROOM_6C, "Pst_pete_room_6cZ", NULL} /* Pst_pete_room_6cZ */,
    {STEEL_DOOR1, "Psteel_door1Z", NULL} /* Psteel_door1Z */,
    {STEEL_DOOR2, "Psteel_door2Z", NULL} /* Psteel_door2Z */,
    {STEEL_DOOR2B, "Psteel_door2bZ", NULL} /* Psteel_door2bZ */,
    {STEEL_DOOR3, "Psteel_door3Z", NULL} /* Psteel_door3Z */,
    {STOOL1, "Pstool1Z", NULL} /* Pstool1Z */,
    {SWIPE_CARD2, "Pswipe_card2Z", NULL} /* Pswipe_card2Z */,
    {SWIVEL_CHAIR1, "Pswivel_chair1Z", NULL} /* Pswivel_chair1Z */,
    {TANK, "PtankZ", NULL} /* PtankZ */,
    {TIGER, "PtigerZ", NULL} /* PtigerZ */,
    {TORPEDO_RACK, "Ptorpedo_rackZ", NULL} /* Ptorpedo_rackZ */,
    {TRAIN_DOOR2, "Ptrain_door2Z", NULL} /* Ptrain_door2Z */,
    {TRAIN_DOOR3, "Ptrain_door3Z", NULL} /* Ptrain_door3Z */,
    {TRAIN_DOOR, "Ptrain_doorZ", NULL} /* Ptrain_doorZ */,
    {TRAINEXTDOOR, "PtrainextdoorZ", NULL} /* PtrainextdoorZ */,
    {TT33MAG, "Ptt33magZ", NULL} /* Ptt33magZ */,
    {TUNING_CONSOLE1, "Ptuning_console1Z", NULL} /* Ptuning_console1Z */,
    {TV1, "Ptv1Z", NULL} /* Ptv1Z */,
    {TV4SCREEN, "Ptv4screenZ", NULL} /* Ptv4screenZ */,
    {TV_HOLDER, "Ptv_holderZ", NULL} /* Ptv_holderZ */,
    {TVSCREEN, "PtvscreenZ", NULL} /* PtvscreenZ */,
    {UZIMAG, "PuzimagZ", NULL} /* PuzimagZ */,
    {VERTDOOR, "PvertdoorZ", NULL} /* PvertdoorZ */,
    {WALLETBOND, "PwalletbondZ", NULL} /* PwalletbondZ */,
    {WINDOW, "PwindowZ", NULL} /* PwindowZ */,
    {WINDOW_COR11, "Pwindow_cor11Z", NULL} /* Pwindow_cor11Z */,
    {WINDOW_LIB_LG1, "Pwindow_lib_lg1Z", NULL} /* Pwindow_lib_lg1Z */,
    {WINDOW_LIB_SM1, "Pwindow_lib_sm1Z", NULL} /* Pwindow_lib_sm1Z */,
    {WOOD_LG_CRATE1, "Pwood_lg_crate1Z", NULL} /* Pwood_lg_crate1Z */,
    {WOOD_LG_CRATE2, "Pwood_lg_crate2Z", NULL} /* Pwood_lg_crate2Z */,
    {WOOD_MD_CRATE3, "Pwood_md_crate3Z", NULL} /* Pwood_md_crate3Z */,
    {WOOD_SM_CRATE4, "Pwood_sm_crate4Z", NULL} /* Pwood_sm_crate4Z */,
    {WOOD_SM_CRATE5, "Pwood_sm_crate5Z", NULL} /* Pwood_sm_crate5Z */,
    {WOOD_SM_CRATE6, "Pwood_sm_crate6Z", NULL} /* Pwood_sm_crate6Z */,
    {WOODEN_TABLE1, "Pwooden_table1Z", NULL} /* Pwooden_table1Z */,
    {WPPKMAG, "PwppkmagZ", NULL} /* PwppkmagZ */,

    {BG_AME_ALL_P_STAN, "Tbg_ame_all_p_stanZ", NULL} /* Tbg_ame_all_p_stanZ */,
    {BG_ARCH_ALL_P_STAN, "Tbg_arch_all_p_stanZ", NULL} /* Tbg_arch_all_p_stanZ */,
    {BG_AREC_ALL_P_STAN, "Tbg_arec_all_p_stanZ", NULL} /* Tbg_arec_all_p_stanZ */,
    {BG_ARK_ALL_P_STAN, "Tbg_ark_all_p_stanZ", NULL} /* Tbg_ark_all_p_stanZ */,
    {BG_ASH_ALL_P_STAN, "Tbg_ash_all_p_stanZ", NULL} /* Tbg_ash_all_p_stanZ */,
    {BG_AZT_ALL_P_STAN, "Tbg_azt_all_p_stanZ", NULL} /* Tbg_azt_all_p_stanZ */,
    {BG_CAT_ALL_P_STAN, "Tbg_cat_all_p_stanZ", NULL} /* Tbg_cat_all_p_stanZ */,
    {BG_CAVE_ALL_P_STAN, "Tbg_cave_all_p_stanZ", NULL} /* Tbg_cave_all_p_stanZ */,
    {BG_CRAD_ALL_P_STAN, "Tbg_crad_all_p_stanZ", NULL} /* Tbg_crad_all_p_stanZ */,
    {BG_CRYP_ALL_P_STAN, "Tbg_cryp_all_p_stanZ", NULL} /* Tbg_cryp_all_p_stanZ */,
    {BG_DAM_ALL_P_STAN, "Tbg_dam_all_p_stanZ", NULL} /* Tbg_dam_all_p_stanZ */,
    {BG_DEPO_ALL_P_STAN, "Tbg_depo_all_p_stanZ", NULL} /* Tbg_depo_all_p_stanZ */,
    {BG_DEST_ALL_P_STAN, "Tbg_dest_all_p_stanZ", NULL} /* Tbg_dest_all_p_stanZ */,
    {BG_DISH_ALL_P_STAN, "Tbg_dish_all_p_stanZ", NULL} /* Tbg_dish_all_p_stanZ */,
    {BG_EAR_ALL_P_STAN, "Tbg_ear_all_p_stanZ", NULL} /* Tbg_imp_all_p_stanZ */,
    {BG_ELD_ALL_P_STAN, "Tbg_eld_all_p_stanZ", NULL} /* Tbg_imp_all_p_stanZ */,
    {BG_IMP_ALL_P_STAN, "Tbg_imp_all_p_stanZ", NULL} /* Tbg_imp_all_p_stanZ */,
    {BG_JUN_ALL_P_STAN, "Tbg_jun_all_p_stanZ", NULL} /* Tbg_jun_all_p_stanZ */,
    {BG_LEE_ALL_P_STAN, "Tbg_lee_all_p_stanZ", NULL} /* Tbg_len_all_p_stanZ */,
    {BG_LEN_ALL_P_STAN, "Tbg_len_all_p_stanZ", NULL} /* Tbg_len_all_p_stanZ */,
    {BG_LIP_ALL_P_STAN, "Tbg_lip_all_p_stanZ", NULL} /* Tbg_oat_all_p_stanZ */,
    {BG_LUE_ALL_P_STAN, "Tbg_lue_all_p_stanZ", NULL} /* Tbg_oat_all_p_stanZ */,
    {BG_OAT_ALL_P_STAN, "Tbg_oat_all_p_stanZ", NULL} /* Tbg_oat_all_p_stanZ */,
    {BG_PAM_ALL_P_STAN, "Tbg_pam_all_p_stanZ", NULL} /* Tbg_pete_all_p_stanZ */,
    {BG_PETE_ALL_P_STAN, "Tbg_pete_all_p_stanZ", NULL} /* Tbg_pete_all_p_stanZ */,
    {BG_REF_ALL_P_STAN, "Tbg_ref_all_p_stanZ", NULL} /* Tbg_ref_all_p_stanZ */,
    {BG_RIT_ALL_P_STAN, "Tbg_rit_all_p_stanZ", NULL} /* Tbg_run_all_p_stanZ */,
    {BG_RUN_ALL_P_STAN, "Tbg_run_all_p_stanZ", NULL} /* Tbg_run_all_p_stanZ */,
    {BG_SEV_ALL_P_STAN, "Tbg_sev_all_p_stanZ", NULL} /* Tbg_sev_all_p_stanZ */,
    {BG_SEVB_ALL_P_STAN, "Tbg_sevb_all_p_stanZ", NULL} /* Tbg_sevb_all_p_stanZ */,
    {BG_SEVX_ALL_P_STAN, "Tbg_sevx_all_p_stanZ", NULL} /* Tbg_sevx_all_p_stanZ */,
    {BG_SILO_ALL_P_STAN, "Tbg_silo_all_p_stanZ", NULL} /* Tbg_silo_all_p_stanZ */,
    {BG_STAT_ALL_P_STAN, "Tbg_stat_all_p_stanZ", NULL} /* Tbg_stat_all_p_stanZ */,
    {BG_TRA_ALL_P_STAN, "Tbg_tra_all_p_stanZ", NULL} /* Tbg_tra_all_p_stanZ */,
    {BG_WAX_ALL_P_STAN, "Tbg_wax_all_p_stanZ", NULL} /* UbriefarchZ */,

    {BRIEFARCH, "UbriefarchZ", NULL} /* UbriefarchZ */,
    {BRIEFARK, "UbriefarkZ", NULL} /* UbriefarkZ */,
    {BRIEFAZT, "UbriefaztZ", NULL} /* UbriefaztZ */,
    {BRIEFCAVE, "UbriefcaveZ", NULL} /* UbriefcaveZ */,
    {BRIEFCONTROL, "UbriefcontrolZ", NULL} /* UbriefcontrolZ */,
    {BRIEFCRAD, "UbriefcradZ", NULL} /* UbriefcradZ */,
    {BRIEFCRYP, "UbriefcrypZ", NULL} /* UbriefcrypZ */,
    {BRIEFDAM, "UbriefdamZ", NULL} /* UbriefdamZ */,
    {BRIEFDEPO, "UbriefdepoZ", NULL} /* UbriefdepoZ */,
    {BRIEFDEST, "UbriefdestZ", NULL} /* UbriefdestZ */,
    {BRIEFJUN, "UbriefjunZ", NULL} /* UbriefjunZ */,
    {BRIEFPETE, "UbriefpeteZ", NULL} /* UbriefpeteZ */,
    {BRIEFRUN, "UbriefrunZ", NULL} /* UbriefrunZ */,
    {BRIEFSEVB, "UbriefsevbZ", NULL} /* UbriefsevbZ */,
    {BRIEFSEVBUNKER, "UbriefsevbunkerZ", NULL} /* UbriefsevbunkerZ */,
    {BRIEFSEVX, "UbriefsevxZ", NULL} /* UbriefsevxZ */,
    {BRIEFSEVXB, "UbriefsevxbZ", NULL} /* UbriefsevxbZ */,
    {BRIEFSILO, "UbriefsiloZ", NULL} /* UbriefsiloZ */,
    {BRIEFSTATUE, "UbriefstatueZ", NULL} /* UbriefstatueZ */,
    {BRIEFTRA, "UbrieftraZ", NULL} /* UbrieftraZ */,

    {MP_SETUPAME, "Ump_setupameZ", NULL} /* Ump_setupameZ */,
    {MP_SETUPARCH, "Ump_setuparchZ", NULL} /* Ump_setuparchZ */,
    {MP_SETUPARK, "Ump_setuparkZ", NULL} /* Ump_setuparkZ */,
    {MP_SETUPASH, "Ump_setupashZ", NULL} /* Ump_setupashZ */,
    {MP_SETUPCAVE, "Ump_setupcaveZ", NULL} /* Ump_setupcaveZ */,
    {MP_SETUPCRAD, "Ump_setupcradZ", NULL} /* Ump_setupcradZ */,
    {MP_SETUPCRYP, "Ump_setupcrypZ", NULL} /* Ump_setupcrypZ */,
    {MP_SETUPDISH, "Ump_setupdishZ", NULL} /* Ump_setupdishZ */,
    {MP_SETUPIMP, "Ump_setupimpZ", NULL} /* Ump_setupimpZ */,
    {MP_SETUPOAT, "Ump_setupoatZ", NULL} /* Ump_setupoatZ */,
    {MP_SETUPREF, "Ump_setuprefZ", NULL} /* Ump_setuprefZ */,
    {MP_SETUPSEVB, "Ump_setupsevbZ", NULL} /* Ump_setupsevbZ */,
    {MP_SETUPSTATUE, "Ump_setupstatueZ", NULL} /* Ump_setupstatueZ */,

    {SETUPARCH, "UsetuparchZ", NULL} /* UsetuparchZ */,
    {SETUPARK, "UsetuparkZ", NULL} /* UsetuparkZ */,
    {SETUPAZT, "UsetupaztZ", NULL} /* UsetupaztZ */,
    {SETUPCAVE, "UsetupcaveZ", NULL} /* UsetupcaveZ */,
    {SETUPCONTROL, "UsetupcontrolZ", NULL} /* UsetupcontrolZ */,
    {SETUPCRAD, "UsetupcradZ", NULL} /* UsetupcradZ */,
    {SETUPCRYP, "UsetupcrypZ", NULL} /* UsetupcrypZ */,
    {SETUPDAM, "UsetupdamZ", NULL} /* UsetupdamZ */,
    {SETUPDEPO, "UsetupdepoZ", NULL} /* UsetupdepoZ */,
    {SETUPDEST, "UsetupdestZ", NULL} /* UsetupdestZ */,
    {SETUPJUN, "UsetupjunZ", NULL} /* UsetupjunZ */,
    {SETUPLEN, "UsetuplenZ", NULL} /* UsetuplenZ */,
    {SETUPPETE, "UsetuppeteZ", NULL} /* UsetuppeteZ */,
    {SETUPRUN, "UsetuprunZ", NULL} /* UsetuprunZ */,
    {SETUPSEVB, "UsetupsevbZ", NULL} /* UsetupsevbZ */,
    {SETUPSEVBUNKER, "UsetupsevbunkerZ", NULL} /* UsetupsevbunkerZ */,
    {SETUPSEVX, "UsetupsevxZ", NULL} /* UsetupsevxZ */,
    {SETUPSEVXB, "UsetupsevxbZ", NULL} /* UsetupsevxbZ */,
    {SETUPSILO, "UsetupsiloZ", NULL} /* UsetupsiloZ */,
    {SETUPSTATUE, "UsetupstatueZ", NULL} /* UsetupstatueZ */,
    {SETUPTRA, "UsetuptraZ", NULL} /* UsetuptraZ */,

    {AMEE, "LameE", NULL} /* LameE */,
    {AMEJ, "LameJ", NULL} /* LameJ */,
#ifdef VERSION_EU
    {AMEP, "LameP", NULL} /* LameP */,
#endif
    {ARCHE, "LarchE", NULL} /* LarchE */,
    {ARCHJ, "LarchJ", NULL} /* LarchJ */,
#ifdef VERSION_EU
    {ARCHP, "LarchP", NULL} /* LarchP */,
#endif
    {ARECE, "LarecE", NULL} /* LarecE */,
    {ARECJ, "LarecJ", NULL} /* LarecJ */,
#ifdef VERSION_EU
    {ARECP, "LarecP", NULL} /* LarecP */,
#endif
    {ARKE, "LarkE", NULL} /* LarkE */,
    {ARKJ, "LarkJ", NULL} /* LarkJ */,
#ifdef VERSION_EU
    {ARKP, "LarkP", NULL} /* LarkP */,
#endif
    {ASHE, "LashE", NULL} /* LashE */,
    {ASHJ, "LashJ", NULL} /* LashJ */,
#ifdef VERSION_EU
    {ASHP, "LashP", NULL} /* LashP */,
#endif
    {AZTE, "LaztE", NULL} /* LaztE */,
    {AZTJ, "LaztJ", NULL} /* LaztJ */,
#ifdef VERSION_EU
    {AZTP, "LaztP", NULL} /* LaztP */,
#endif
    {CATE, "LcatE", NULL} /* LcatE */,
    {CATJ, "LcatJ", NULL} /* LcatJ */,
#ifdef VERSION_EU
    {CATP, "LcatP", NULL} /* LcatP */,
#endif
    {CAVEE, "LcaveE", NULL} /* LcaveE */,
    {CAVEJ, "LcaveJ", NULL} /* LcaveJ */,
#ifdef VERSION_EU
    {CAVEP, "LcaveP", NULL} /* LcaveP */,
#endif
    {CRADE, "LcradE", NULL} /* LcradE */,
    {CRADJ, "LcradJ", NULL} /* LcradJ */,
#ifdef VERSION_EU
    {CRADP, "LcradP", NULL} /* LcradP */,
#endif
    {CRYPE, "LcrypE", NULL} /* LcrypE */,
    {CRYPJ, "LcrypJ", NULL} /* LcrypJ */,
#ifdef VERSION_EU
    {CRYPP, "LcrypP", NULL} /* LcrypP */,
#endif
    {DAME, "LdamE", NULL} /* LdamE */,
    {DAMJ, "LdamJ", NULL} /* LdamJ */,
#ifdef VERSION_EU
    {DAMP, "LdamP", NULL} /* LdamP */,
#endif
    {DEPOE, "LdepoE", NULL} /* LdepoE */,
    {DEPOJ, "LdepoJ", NULL} /* LdepoJ */,
#ifdef VERSION_EU
    {DEPOP, "LdepoP", NULL} /* LdepoP */,
#endif
    {DESTE, "LdestE", NULL} /* LdestE */,
    {DESTJ, "LdestJ", NULL} /* LdestJ */,
#ifdef VERSION_EU
    {DESTP, "LdestP", NULL} /* LdestP */,
#endif
    {DISHE, "LdishE", NULL} /* LdishE */,
    {DISHJ, "LdishJ", NULL} /* LdishJ */,
#ifdef VERSION_EU
    {DISHP, "LdishP", NULL} /* LdishP */,
#endif
    {EARE, "LearE", NULL} /* LearE */,
    {EARJ, "LearJ", NULL} /* LearJ */,
#ifdef VERSION_EU
    {EARP, "LearP", NULL} /* LearP */,
#endif
    {ELDE, "LeldE", NULL} /* LeldE */,
    {ELDJ, "LeldJ", NULL} /* LeldJ */,
#ifdef VERSION_EU
    {ELDP, "LeldP", NULL} /* LeldP */,
#endif
    {GUNE, "LgunE", NULL} /* LgunE */,
    {GUNJ, "LgunJ", NULL} /* LgunJ */,
#ifdef VERSION_EU
    {GUNP, "LgunP", NULL} /* LgunP */,
#endif
    {IMPE, "LimpE", NULL} /* LimpE */,
    {IMPJ, "LimpJ", NULL} /* LimpJ */,
#ifdef VERSION_EU
    {IMPP, "LimpP", NULL} /* LimpP */,
#endif
    {JUNE, "LjunE", NULL} /* LjunE */,
    {JUNJ, "LjunJ", NULL} /* LjunJ */,
#ifdef VERSION_EU
    {JUNP, "LjunP", NULL} /* LjunP */,
#endif
    {LEEE, "LleeE", NULL} /* LleeE */,
    {LEEJ, "LleeJ", NULL} /* LleeJ */,
#ifdef VERSION_EU
    {LEEP, "LleeP", NULL} /* LleeP */,
#endif
    {LENE, "LlenE", NULL} /* LlenE */,
    {LENJ, "LlenJ", NULL} /* LlenJ */,
#ifdef VERSION_EU
    {LENP, "LlenP", NULL} /* LlenP */,
#endif
    {LIPE, "LlipE", NULL} /* LlipE */,
    {LIPJ, "LlipJ", NULL} /* LlipJ */,
#ifdef VERSION_EU
    {LIPP, "LlipP", NULL} /* LlipP */,
#endif
    {LUEE, "LlueE", NULL} /* LlueE */,
    {LUEJ, "LlueJ", NULL} /* LlueJ */,
#ifdef VERSION_EU
    {LUEP, "LlueP", NULL} /* LlueP */,
#endif
    {MISCE, "LmiscE", NULL} /* LmiscE */,
    {MISCJ, "LmiscJ", NULL} /* LmiscJ */,
#ifdef VERSION_EU
    {MISCP, "LmiscP", NULL} /* LmiscP */,
#endif
    {MPMENUE, "LmpmenuE", NULL} /* LmpmenuE */,
    {MPMENUJ, "LmpmenuJ", NULL} /* LmpmenuJ */,
#ifdef VERSION_EU
    {MPMENUP, "LmpmenuP", NULL} /* LmpmenuP */,
#endif
    {MPWEAPONSE, "LmpweaponsE", NULL} /* LmpweaponsE */,
    {MPWEAPONSJ, "LmpweaponsJ", NULL} /* LmpweaponsJ */,
#ifdef VERSION_EU
    {MPWEAPONSP, "LmpweaponsP", NULL} /* LmpweaponsP */,
#endif
    {OATE, "LoatE", NULL} /* LoatE */,
    {OATJ, "LoatJ", NULL} /* LoatJ */,
#ifdef VERSION_EU
    {OATP, "LoatP", NULL} /* LoatP */,
#endif
    {OPTIONSE, "LoptionsE", NULL} /* LoptionsE */,
    {OPTIONSJ, "LoptionsJ", NULL} /* LoptionsJ */,
#ifdef VERSION_EU
    {OPTIONSP, "LoptionsP", NULL} /* LoptionsP */,
#endif
    {PAME, "LpamE", NULL} /* LpamE */,
    {PAMJ, "LpamJ", NULL} /* LpamJ */,
#ifdef VERSION_EU
    {PAMP, "LpamP", NULL} /* LpamP */,
#endif
    {PETEE, "LpeteE", NULL} /* LpeteE */,
    {PETEJ, "LpeteJ", NULL} /* LpeteJ */,
#ifdef VERSION_EU
    {PETEP, "LpeteP", NULL} /* LpeteP */,
#endif
    {PROPOBJE, "LpropobjE", NULL} /* LpropobjE */,
    {PROPOBJJ, "LpropobjJ", NULL} /* LpropobjJ */,
#ifdef VERSION_EU
    {PROPOBJP, "LpropobjP", NULL} /* LpropobjP */,
#endif
    {REFE, "LrefE", NULL} /* LrefE */,
    {REFJ, "LrefJ", NULL} /* LrefJ */,
#ifdef VERSION_EU
    {REFP, "LrefP", NULL} /* LrefP */,
#endif
    {RITE, "LritE", NULL} /* LritE */,
    {RITJ, "LritJ", NULL} /* LritJ */,
#ifdef VERSION_EU
    {RITP, "LritP", NULL} /* LritP */,
#endif
    {RUNE, "LrunE", NULL} /* LrunE */,
    {RUNJ, "LrunJ", NULL} /* LrunJ */,
#ifdef VERSION_EU
    {RUNP, "LrunP", NULL} /* LrunP */,
#endif
    {SEVE, "LsevE", NULL} /* LsevE */,
    {SEVJ, "LsevJ", NULL} /* LsevJ */,
#ifdef VERSION_EU
    {SEVP, "LsevP", NULL} /* LsevP */,
#endif
    {SEVBE, "LsevbE", NULL} /* LsevbE */,
    {SEVBJ, "LsevbJ", NULL} /* LsevbJ */,
#ifdef VERSION_EU
    {SEVBP, "LsevbP", NULL} /* LsevbP */,
#endif
    {SEVXE, "LsevxE", NULL} /* LsevxE */,
    {SEVXJ, "LsevxJ", NULL} /* LsevxJ */,
#ifdef VERSION_EU
    {SEVXP, "LsevxP", NULL} /* LsevxP */,
#endif
    {SEVXBE, "LsevxbE", NULL} /* LsevxbE */,
    {SEVXBJ, "LsevxbJ", NULL} /* LsevxbJ */,
#ifdef VERSION_EU
    {SEVXBP, "LsevxbP", NULL} /* LsevxbP */,
#endif
    {SHOE, "LshoE", NULL} /* LshoE */,
    {SHOJ, "LshoJ", NULL} /* LshoJ */,
#ifdef VERSION_EU
    {SHOP, "LshoP", NULL} /* LshoP */,
#endif
    {SILOE, "LsiloE", NULL} /* LsiloE */,
    {SILOJ, "LsiloJ", NULL} /* LsiloJ */,
#ifdef VERSION_EU
    {SILOP, "LsiloP", NULL} /* LsiloP */,
#endif
    {STATE, "LstatE", NULL} /* LstatE */,
    {STATJ, "LstatJ", NULL} /* LstatJ */,
#ifdef VERSION_EU
    {STATP, "LstatP", NULL} /* LstatP */,
#endif
    {TITLEE, "LtitleE", NULL} /* LtitleE */,
    {TITLEJ, "LtitleJ", NULL} /* LtitleJ */,
#ifdef VERSION_EU
    {TITLEP, "LtitleP", NULL} /* LtitleP */,
#endif
    {TRAE, "LtraE", NULL} /* LtraE */,
    {TRAJ, "LtraJ", NULL} /* LtraJ */,
#ifdef VERSION_EU
    {TRAP, "LtraP", NULL} /* LtraP */,
#endif
    {WAXE, "LwaxE", NULL} /* LwaxE */,
    {WAXJ, "LwaxJ", NULL} /* LwaxJ */,
#ifdef VERSION_EU
    {WAXP, "LwaxP", NULL} /* LwaxP */,
#endif
    
    {OBENDSEG, "ob/ob_end.seg", NULL} /* ob__ob_end_seg */,
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0}
};


