#ifndef _GEVR_ROM_MANIFEST_H_
#define _GEVR_ROM_MANIFEST_H_

/**
 * Where each of GoldenEye's files sits inside a retail cartridge.
 *
 * Rows are in the same order as file_resource_table, so entry i here describes
 * file_resource_table[i]. A zero offset means this ROM has no data for that
 * entry - the table is shared across regions, and a US cartridge does not
 * carry the PAL-only levels.
 *
 * Generated by tools/gevr_gen_rom_manifest.py from the upstream decomp's
 * scripts/filelist.<region>.csv. Offsets only; the player supplies the bytes.
 */

struct gevrRomFile {
	unsigned int offset;      /* byte offset into the ROM image, 0 if absent */
	unsigned int size;        /* length in the ROM, as stored                */
	unsigned int compressed;  /* non-zero if 1172-compressed                 */
};

extern const struct gevrRomFile g_GevrRomFiles[];
extern const unsigned int g_GevrRomFileCount;

#endif
