#!/usr/bin/env python3
"""
Emit the list of every animation header in the ANIMATION_DATA segment, as the
PTR_ANIM_* names that assets/animationtable_data.h defines.

port/src/gevr_romswap.c walks this list to byte-swap each cartridge animation
header and its bit descriptors after the segment is copied out of the ROM. The
names are emitted rather than the numbers so the values stay owned by the
header; regenerate this if the header changes.

Usage:
    python tools/gevr_gen_anim_offsets.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "assets", "animationtable_data.h")
DST = os.path.join(REPO, "port", "src", "gevr_anim_offsets.inc")

names = []
with open(SRC, encoding="utf-8") as f:
    for line in f:
        m = re.match(r"\s*#define\s+(PTR_ANIM_\w+)\s+0x[0-9A-Fa-f]+", line)
        if m:
            names.append(m.group(1))

with open(DST, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* GENERATED by tools/gevr_gen_anim_offsets.py from\n")
    f.write(" * assets/animationtable_data.h - do not edit. */\n")
    for n in names:
        f.write("\t%s,\n" % n)

print("%s: %d animation headers" % (os.path.relpath(DST, REPO), len(names)))
