#!/usr/bin/env python3
"""
Turn the hand patches (tools/handpatch/*.patch.json) into C data for the game
(issue #9). Writes port/src/gevr_handpatch_data.c, read by
port/src/gevr_handpatch.c when a model loads.

The patches hold only what we add - triangles over ROM vertices named by
DL node (its offset in the cartridge file) and index, weights over ROM
vertices for new points, our texture coordinates and shade, and a
fingerprint per node - so the generated file holds no ROM data either.

A corner's shade is its own "c" ([r, g, b, a]), else its group's "shade";
"inherit": true on a ROM vertex's corner draws it in that vertex's colour.

Usage
-----
    python tools/gevr_handpatch_gen.py

Run it after tools/blender/gevr_hands_patch.py changes a patch; commit both.
"""

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "tools", "handpatch")
OUT = os.path.join(REPO, "port", "src", "gevr_handpatch_data.c")


def main():
    nodes, corners, mixes, tris, groups, parts, models = [], [], [], [], [], [], []
    for path in sorted(glob.glob(os.path.join(SRC, "*.patch.json"))):
        with open(path, encoding="utf-8") as f:
            patch = json.load(f)
        first_part = len(parts)
        for part in patch["parts"]:
            first_node = len(nodes)
            for n, info in sorted(part["nodes"].items()):
                nodes.append((int(n, 16), info["numvtx"], int(info["fingerprint"], 16)))
            first_group = len(groups)
            for g in part["groups"]:
                first_corner = len(corners)
                shade = g.get("shade", [255, 255, 255, 255])
                for v in g["verts"]:
                    cn = tuple(v.get("c", shade))
                    flags = 1 if v.get("inherit") and "mix" not in v else 0
                    if "mix" in v:
                        first_mix = len(mixes)
                        for node, idx, w in v["mix"]:
                            mixes.append((int(node, 16), idx, w))
                        corners.append((0, -1, v["s"], v["t"], v["mtx"], len(v["mix"]), first_mix) + cn + (flags,))
                    else:
                        corners.append((int(v["node"], 16), v["ref"], v["s"], v["t"], v["mtx"], 0, 0) + cn + (flags,))
                first_tri = len(tris)
                for t in g["tris"]:
                    tris.append(tuple(t))
                if len(g["verts"]) > 1024:
                    # hpEmitGroup's tables hold 1024 corners; a bigger group draws nothing
                    raise SystemExit("%s: a group of %d corners (at most 1024)" % (patch["model"], len(g["verts"])))
                groups.append((int(g["tex"], 16), first_corner, len(g["verts"]), first_tri, len(g["tris"])))
            parts.append((int(part["host"], 16), first_node, len(part["nodes"]),
                          first_group, len(part["groups"])))
        if len(parts) - first_part > 9:
            # each part takes 5 of a model buffer's 48 allocations (gevr_handpatch.c)
            raise SystemExit("%s: %d parts (at most 9)" % (patch["model"], len(parts) - first_part))
        models.append((patch["model"], first_part, len(parts) - first_part))

    for c in corners:
        if not (-32768 <= c[2] <= 32767 and -32768 <= c[3] <= 32767):
            raise SystemExit("texture coordinate out of range: %s" % (c,))
        if not (0 <= c[4] <= 255 and 0 <= c[5] <= 255 and all(0 <= x <= 255 for x in c[7:11])):
            raise SystemExit("matrix, weight count or shade out of range: %s" % (c,))
    for t in tris:
        if max(t) > 65535:
            raise SystemExit("group too large")
    # first-corner, first-triangle and first-weight indices are u16
    for what, n in (("corners", len(corners)), ("triangles", len(tris)), ("weights", len(mixes)),
                    ("groups", len(groups)), ("nodes", len(nodes))):
        if n > 65535:
            raise SystemExit("too many %s for u16 indices: %d" % (what, n))

    L = []
    w = L.append
    w("/*")
    w(" * Hand and arm patches for the first-person models (issue #9).")
    w(" *")
    w(" * GENERATED by tools/gevr_handpatch_gen.py from tools/handpatch/<model>.patch.json")
    w(" * (made in Blender by tools/blender/gevr_hands_patch.py). Do not edit.")
    w(" *")
    w(" * Our data only: triangles over ROM vertices named by DL node (cartridge")
    w(" * offset) and index, weights over ROM vertices for new points, our texture")
    w(" * coordinates and shade, and a fingerprint of each node's vertex block.")
    w(" */")
    w("")
    w('#include "gevr_handpatch.h"')
    w("")
    w("const struct gevrHpNode g_gevrHpNodes[] = {")
    for n in nodes:
        w("    { 0x%04x, %d, 0x%08xu }," % n)
    w("};")
    w("")
    w("const struct gevrHpCorner g_gevrHpCorners[] = {")
    for c in corners:
        w("    { 0x%04x, %d, %d, %d, %d, %d, %d, { %d, %d, %d, %d }, %d }," % c)
    w("};")
    w("")
    w("const struct gevrHpMix g_gevrHpMixes[] = {")
    for m in mixes:
        w("    { 0x%04x, %d, %.6ff }," % m)
    w("};")
    w("")
    w("const u16 g_gevrHpTris[][3] = {")
    for i in range(0, len(tris), 6):
        w("    " + " ".join("{ %d, %d, %d }," % t for t in tris[i:i + 6]))
    w("};")
    w("")
    w("const struct gevrHpGroup g_gevrHpGroups[] = {")
    for g in groups:
        w("    { 0x%03x, %d, %d, %d, %d }," % g)
    w("};")
    w("")
    w("const struct gevrHpPart g_gevrHpParts[] = {")
    for p in parts:
        w("    { 0x%04x, %d, %d, %d, %d }," % p)
    w("};")
    w("")
    w("const struct gevrHpModel g_gevrHpModels[] = {")
    for name, fp, np_ in models:
        w('    { "%s", %d, %d },' % (name, fp, np_))
    w("};")
    w("")
    w("const s32 g_gevrHpNumModels = %d;" % len(models))
    w("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print("%s: %d models, %d parts, %d groups, %d triangles, %d corners, %d weights"
          % (os.path.relpath(OUT, REPO), len(models), len(parts), len(groups), len(tris),
             len(corners), len(mixes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
