/*
 * GENERATED by tools/gevr_implicit_decls.py - do not edit.
 *
 * Prototypes for functions that return a pointer and that at least one file
 * calls without a declaration in scope. C then assumes they return int, which
 * on the N64 was the width of a pointer and here is half of one: the call kept
 * the low 32 bits of the address and faulted far away. Each is copied from the
 * definition, with the file that defines it and the files that called it blind.
 */
#ifndef _GEVR_IMPLICIT_PROTOS_H_
#define _GEVR_IMPLICIT_PROTOS_H_

/* src/game/ob.c; called blind from src/game/bg.c */
char *bgDebPrintROOMID(s32 roomId);
/* src/game/bg.c; called blind from src/game/mpmenu.c */
Gfx* bgScissorCurrentPlayerViewDefault(Gfx* arg0);
/* src/game/bondinv.c; called blind from src/game/propobj.c */
u8 *bondinvGetActivatedTextObject(ObjectRecord *obj);
/* src/game/bondinv.c; called blind from src/game/propobj.c */
u8 *bondinvGetActivatedTextWeapon(ITEM_IDS weaponnum);
/* src/game/bondinv.c; called blind from src/game/options.c */
u16 *bondinvGetFirstTitlebyIndex(s32 index);
/* src/game/bondinv.c; called blind from src/game/options.c */
u16 *bondinvGetLongNameByIndex(s32 index);
/* src/game/bondinv.c; called blind from src/game/options.c */
u16 *bondinvGetSecondTitlebyIndex(s32 index);
/* src/game/bondview2.c; called blind from src/game/bg.c, src/game/gun.c */
coord3d * bondviewGetCurrentPlayersPosition3(void);
/* src/game/chrprop.c; called blind from src/game/vtxstore.c */
PropRecord *chrpropGetActiveTail(void);
/* src/game/bondview.c; called blind from src/game/glass.c */
Mtx *currentPlayerGetMatrix10C8(void);
/* src/game/bondview.c; called blind from src/game/bondview2.c */
void *currentPlayerSetMatrix10CC(Mtxf *matrix);
/* src/game/radar.c; called blind from src/game/bondview2.c */
Gfx *display_red_blue_on_radar(Gfx *DL);
/* src/game/propobj.c; called blind from src/game/prop.c */
PropRecord* doorInit(DoorRecord* door, coord3d* pos, Mtxf* mtx, StandTile* stan, coord3d* coord, coord3d* centre);
/* src/game/dyn.c; called blind from src/game/bondview2.c, src/game/gun.c, src/game/gunfire.c, src/game/propobj.c, src/game/title.c */
void *dynAllocate(s32 size);
/* src/game/dyn.c; called blind from src/game/bondview2.c */
Light *dynAllocateLights(s32 count);
/* src/game/dyn.c; called blind from src/game/bondview2.c, src/game/glass.c */
Mtx *dynAllocateMatrix(void);
/* src/game/dyn.c; called blind from src/game/propobj.c */
Vtx *dynAllocateVertices(s32 count);
/* src/game/file2.c; called blind from src/game/file.c, src/game/front.c */
u8 * getPlayerWeaponBufferForHand(GUNHAND hand);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
u16 *get_ptr_first_title_line_item(ITEM_IDS item);
/* src/game/gun.c; called blind from src/game/bondview2.c */
ModelFileHeader *get_ptr_itemheader_in_hand(GUNHAND hand);
/* src/game/gunfire.c; called blind from src/game/bondinv.c, src/game/front.c */
u16 *get_ptr_long_watch_text_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
u16 *get_ptr_second_title_line_item(ITEM_IDS item);
/* src/game/objective_status.c; called blind from src/game/options.c */
u8 * get_ptr_text_for_watch_breifing_page(WATCH_BRIEFING_PAGE page);
/* src/game/objective_status.c; called blind from src/game/options.c */
u8 * get_text_for_objective(int objectiveIndex);
/* src/game/gunfire.c; called blind from src/game/options.c */
Gfx *gunDrawWatchAmmoDisplay(Gfx *gdl);
/* src/game/propobj.c; called blind from src/game/chrai.c */
PropRecord *hatCreateForChr(ChrRecord *chr, s32 modelnum, u32 flags);
/* src/game/indy_comms.c; called blind from src/game/ramromreplay.c */
u8 * indycommHostCheckFileExists(char *name, s32 *size);
/* src/game/language.c; called blind from src/game/gunfire.c */
u8 * langGet(s32 slotID);
/* src/mema.c; called blind from src/game/bg.c */
void *memaAlloc(u32 amount);
/* src/game/propobj.c; called blind from src/game/gunfire.c */
Gfx *process_monitor_animation_microcode(Model *model, ModelNode *node, MonitorRecord *screen, Gfx *gdl, s32 arg4, s32 arg5);
/* src/game/title.c; called blind from src/game/front.c */
Gfx *renderGunbarrelEyeIntroSequence (Gfx *gdl);
/* src/game/title.c; called blind from src/game/front.c */
Gfx *retrieve_display_rareware_logo(Gfx *gdl);
/* src/game/gunfire.c; called blind from src/game/options.c */
Gfx *set_enviro_fog_for_items_in_solo_watch_menu(Gfx *gdl, ITEM_IDS itemid, Mtxf *mtx, s32 arg3, s32 arg4);
/* src/game/loadobjectmodel.c; called blind from src/game/propobj.c */
ObjectRecord *setupFindObjForReuse(s32 wanttype, ObjectRecord **offscreenobjptr, ObjectRecord **anyobjptr, bool musthaveprop, bool musthavemodel, ModelFileHeader *modeldef);
/* src/game/sky.c; called blind from src/game/lv.c */
Gfx *skyRender(Gfx *gdl);
/* src/game/propobj.c; called blind from src/game/player.c */
PropRecord *something_with_generating_object(ChrRecord *self, s32 propid, ITEM_IDS itemid, s32 flags, WeaponObjRecord *weapon, ItemModelFileRecord *prop_header);
/* src/game/gunfire.c; called blind from src/game/propobj.c */
Gfx *sub_GAME_7F061E18(Gfx *gdl, BeamRecord *flash, s32 arg2);
/* src/game/sky.c; called blind from src/game/tex.c */
Gfx* sub_GAME_7F09343C(Gfx*, s32);
/* src/game/unk_092E50.c; called blind from src/game/tex.c */
Gfx* sub_GAME_7F09365C(Gfx *gdl, s32 arg1);
/* src/memp.c; called blind from src/game/stan.c */
const char *tokenFind(s32 arg0, const char *arg1);
/* src/game/gunfire.c; called blind from src/game/options.c */
#endif
