/*
 * GENERATED by tools/gevr_implicit_decls.py - do not edit.
 *
 * Prototypes for functions that at least one file calls without a declaration
 * in scope and whose return type an implicit int mangles on this host:
 *  - pointers: the call kept the low 32 bits of the address and faulted far away;
 *  - s8/u8/s16/u16: MIPS callees extended these to the full register, AArch64
 *    callers do it themselves, so the implicit int saw garbage upper bits
 *    (joyGetStickY() read -80 as 176);
 *  - f32/f64: returned in a float register the caller never read.
 * Each is copied from the definition, with the file that defines it and the
 * files that called it blind.
 */
#ifndef _GEVR_IMPLICIT_PROTOS_H_
#define _GEVR_IMPLICIT_PROTOS_H_

/* src/fr.c; called blind from src/game/gunfire.c */
u16 viGetPerspNorm(void);
/* src/fr.c; called blind from src/game/mpmenu.c */
s16 viGetViewHeight(void);
/* src/fr.c; called blind from src/game/mpmenu.c */
s16 viGetViewLeft(void);
/* src/fr.c; called blind from src/game/mpmenu.c */
s16 viGetViewTop(void);
/* src/fr.c; called blind from src/game/mpmenu.c */
s16 viGetViewWidth(void);
/* src/fr.c; called blind from src/debugmenu.c */
s16 viGetX(void);
/* src/fr.c; called blind from src/debugmenu.c */
s16 viGetY(void);
/* src/game/bg.c; called blind from src/game/bg.c */
bool bgProjectRoomCoordToScreen(coord3d* src, coord3d* dst);
/* src/game/bg.c; called blind from src/game/mpmenu.c */
Gfx* bgScissorCurrentPlayerViewDefault(Gfx* arg0);
/* src/game/bg.c; called blind from src/game/chrprop.c, src/game/propobj.c */
bool bgTestRayIntersectsBbox(coord3d *origin, coord3d *dir, s32 *bbox_min, s32 *bbox_max);
/* src/game/bondinv.c; called blind from src/game/propobj.c */
bool bondinvCheckHasKeyFlags(u32 wantkeyflags);
/* src/game/bondinv.c; called blind from src/game/propobj.c */
u8 *bondinvGetActivatedTextObject(ObjectRecord *obj);
/* src/game/bondinv.c; called blind from src/game/propobj.c */
u8 *bondinvGetActivatedTextWeapon(ITEM_IDS weaponnum);
/* src/game/bondinv.c; called blind from src/game/options.c */
u16 *bondinvGetFirstTitlebyIndex(s32 index);
/* src/game/bondinv.c; called blind from src/game/options.c */
u16 *bondinvGetLongNameByIndex(s32 index);
/* src/game/bondinv.c; called blind from src/game/options.c */
u16 *bondinvGetSecondTitlebyIndex(s32 index);
/* src/game/bondinv.c; called blind from src/game/gunfire.c */
bool bondinvHasGEKey(void);
/* src/game/bondinv.c; called blind from src/game/objective_status.c */
bool bondinvHasPropInInv(PropRecord *prop);
/* src/game/bondview.c; called blind from src/game/glass.c */
Mtx *currentPlayerGetMatrix10C8(void);
/* src/game/bondview.c; called blind from src/game/bondview2.c */
void *currentPlayerSetMatrix10CC(Mtxf *matrix);
/* src/game/bondview2.c; called blind from src/game/bg.c, src/game/gun.c */
coord3d * bondviewGetCurrentPlayersPosition3(void);
/* src/game/bondview2.c; called blind from src/game/debugmenu_handler.c */
bool currentPlayerGetXAutoAimEnabled(void);
/* src/game/bondview2.c; called blind from src/game/debugmenu_handler.c */
bool currentPlayerGetYAutoAimEnabled(void);
/* src/game/bondview2.c; called blind from src/game/debugmenu_handler.c */
PropRecord* getCurrentPlayerProp(void);
/* src/game/bondview2.c; called blind from src/game/debugmenu_handler.c */
u8 get_bondata_invincible_flag(void);
/* src/game/cheat.c; called blind from src/game/prop.c, src/game/radar.c */
bool cheatIsActive(CHEAT_ID cheat);
/* src/game/chraction.c; called blind from src/game/objective_status.c */
bool chrHasStageFlag(ChrRecord *self, s32 flags);
/* src/game/chrprop.c; called blind from src/game/vtxstore.c */
PropRecord *chrpropGetActiveTail(void);
/* src/game/chrprop.c; called blind from src/game/propobj.c */
bool doorIsPadlockFree(DoorRecord* door);
/* src/game/dyn.c; called blind from src/game/bondview2.c, src/game/gun.c, src/game/gunfire.c, src/game/propobj.c, src/game/title.c */
void *dynAllocate(s32 size);
/* src/game/dyn.c; called blind from src/game/bondview2.c */
Light *dynAllocateLights(s32 count);
/* src/game/dyn.c; called blind from src/game/bondview2.c, src/game/glass.c */
Mtx *dynAllocateMatrix(void);
/* src/game/dyn.c; called blind from src/game/propobj.c */
Vtx *dynAllocateVertices(s32 count);
/* src/game/file2.c; called blind from src/game/front.c */
bool fileIsAztecCompletedOnSecretOr00ForFolder(s32 folder);
/* src/game/file2.c; called blind from src/game/front.c */
bool fileIsCradleCompletedAnyFolder(void);
/* src/game/file2.c; called blind from src/game/front.c */
bool fileIsCradleCompletedForFolder(s32 folder);
/* src/game/file2.c; called blind from src/game/front.c */
bool fileIsEgyptCompletedOn00ForFolder(int foldernum);
/* src/game/file2.c; called blind from src/game/file.c, src/game/front.c */
u8 * getPlayerWeaponBufferForHand(GUNHAND hand);
/* src/game/front.c; called blind from src/game/mpmenu.c */
char *frontGetPlayersFavoriteWeaponInHand(int player, int hand);
/* src/game/front.c; called blind from src/game/bondview2.c */
u16 get_player_mp_char_body(s32 player);
/* src/game/front.c; called blind from src/game/bondview2.c */
u16 get_player_mp_char_head(s32 player);
/* src/game/gun.c; called blind from src/game/bondview2.c */
ModelFileHeader *get_ptr_itemheader_in_hand(GUNHAND hand);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_depth_offset_solo_watch_menu_inventory_page_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_depth_on_solo_watch_menu_page_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_horizontal_offset_on_solo_watch_menu_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_lateral_position_solo_watch_menu_main_page_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
u16 *get_ptr_first_title_line_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c, src/game/front.c */
u16 *get_ptr_long_watch_text_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
u16 *get_ptr_second_title_line_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_vertical_offset_on_solo_watch_menu_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_vertical_position_solo_watch_menu_main_page_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_xrotation_solo_watch_menu_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/bondinv.c */
f32 get_yrotation_solo_watch_menu_for_item(ITEM_IDS item);
/* src/game/gunfire.c; called blind from src/game/options.c */
Gfx *gunDrawWatchAmmoDisplay(Gfx *gdl);
/* src/game/gunfire.c; called blind from src/game/options.c */
Gfx *set_enviro_fog_for_items_in_solo_watch_menu(Gfx *gdl, ITEM_IDS itemid, Mtxf *mtx, s32 arg3, s32 arg4);
/* src/game/gunfire.c; called blind from src/game/propobj.c */
Gfx *sub_GAME_7F061E18(Gfx *gdl, BeamRecord *flash, s32 arg2);
/* src/game/indy_comms.c; called blind from src/game/ramromreplay.c */
u8 * indycommHostCheckFileExists(char *name, s32 *size);
/* src/game/language.c; called blind from src/game/gunfire.c */
u8 * langGet(s32 slotID);
/* src/game/lightfixture.c; called blind from src/game/bg.c, src/game/chrprop.c */
bool check_if_imageID_is_light(s32 imageID);
/* src/game/line_tri_intersect.c; called blind from src/game/bg.c, src/game/propobj.c */
bool intersectRayTriangle(Vertex *vertex0, Vertex *vertex1, Vertex *vertex2, coord3d *vertexOffset, coord3d *rayStart, coord3d *linePoint, coord3d *rayDirection, HitThing *hit);
/* src/game/loadobjectmodel.c; called blind from src/game/propobj.c */
ObjectRecord *setupFindObjForReuse(s32 wanttype, ObjectRecord **offscreenobjptr, ObjectRecord **anyobjptr, bool musthaveprop, bool musthavemodel, ModelFileHeader *modeldef);
/* src/game/model.c; called blind from src/game/objecthandler.c */
bool modelTestRayIntersectsNodeBBox(Model *model, ModelNode *node, coord3d *pos, coord3d *dir);
/* src/game/model.c; called blind from src/game/initactorpropstuff.c */
u16 sub_GAME_7F06D2E4(s32 jointnum, s32 flip, ModelSkeleton *skeleton, ModelAnimation *anim, s32 frame, coord16 *out);
/* src/game/ob.c; called blind from src/game/bg.c */
char *bgDebPrintROOMID(s32 roomId);
/* src/game/objective_status.c; called blind from src/game/options.c */
u8 * get_ptr_text_for_watch_breifing_page(WATCH_BRIEFING_PAGE page);
/* src/game/objective_status.c; called blind from src/game/options.c */
u8 * get_text_for_objective(int objectiveIndex);
/* src/game/objective_status.c; called blind from src/boss.c, src/game/options.c */
bool objectiveIsAllComplete(void);
/* src/game/propobj.c; called blind from src/game/prop.c */
PropRecord* doorInit(DoorRecord* door, coord3d* pos, Mtxf* mtx, StandTile* stan, coord3d* coord, coord3d* centre);
/* src/game/propobj.c; called blind from src/game/propobj.c */
bool doorIsClosed(DoorRecord *door);
/* src/game/propobj.c; called blind from src/game/chrprop.c */
bool doorTestForInteract(PropRecord *prop);
/* src/game/propobj.c; called blind from src/game/chrai.c */
PropRecord *hatCreateForChr(ChrRecord *chr, s32 modelnum, u32 flags);
/* src/game/propobj.c; called blind from src/game/bondview2.c */
bool is_clock_drawn_onscreen(void);
/* src/game/propobj.c; called blind from src/game/objective_status.c */
bool objGetOnscreenRenderBounds(PropRecord *prop, coord3d *arg1, struct coord2d *arg2, struct coord2d *arg3);
/* src/game/propobj.c; called blind from src/game/chrprop.c */
bool objTestForInteract(PropRecord* prop);
/* src/game/propobj.c; called blind from src/game/gunfire.c */
Gfx *process_monitor_animation_microcode(Model *model, ModelNode *node, MonitorRecord *screen, Gfx *gdl, s32 arg4, s32 arg5);
/* src/game/propobj.c; called blind from src/game/chr.c, src/game/propobj.c */
bool propobjFindHit(Model *model, ModelNode *startNode, coord3d *rayPos, coord3d *rayDir, struct HitThing *hitthing, s32 *dstmtxindex, ModelNode **dstnode);
/* src/game/propobj.c; called blind from src/game/player.c */
PropRecord *something_with_generating_object(ChrRecord *self, s32 propid, ITEM_IDS itemid, s32 flags, WeaponObjRecord *weapon, ItemModelFileRecord *prop_header);
/* src/game/radar.c; called blind from src/game/bondview2.c */
Gfx *display_red_blue_on_radar(Gfx *DL);
/* src/game/sky.c; called blind from src/game/lv.c */
Gfx *skyRender(Gfx *gdl);
/* src/game/sky.c; called blind from src/game/tex.c */
Gfx* sub_GAME_7F09343C(Gfx*, s32);
/* src/game/stan.c; called blind from src/game/stan.c */
bool stanTileHasZeroArea(StandTile *tile);
/* src/game/title.c; called blind from src/game/front.c */
Gfx *renderGunbarrelEyeIntroSequence (Gfx *gdl);
/* src/game/title.c; called blind from src/game/front.c */
Gfx *retrieve_display_rareware_logo(Gfx *gdl);
/* src/game/unk_092E50.c; called blind from src/game/tex.c */
Gfx* sub_GAME_7F09365C(Gfx *gdl, s32 arg1);
/* src/init.c; called blind from src/audi.c */
void *setSPToEnd(u8 *stack, u32 size);
/* src/joy.c; called blind from src/game/options.c */
s8 joy7000C174(s8 contpadnum);
/* src/joy.c; called blind from src/game/options.c */
s8 joy7000C284(s8 contpadnum);
/* src/joy.c; called blind from src/game/spectrum.c */
u16 joyGetButtons(s8 contpadnum, u16 mask);
/* src/joy.c; called blind from src/game/options.c */
u16 joyGetButtonsPressedThisFrame(s8 contpadnum, u16 mask);
/* src/joy.c; called blind from src/game/options.c */
s8 joyGetControllerCount(void);
/* src/joy.c; called blind from src/game/options.c */
s8 joyGetStickX(s8 contpadnum);
/* src/joy.c; called blind from src/game/options.c */
s8 joyGetStickY(s8 contpadnum);
/* src/mema.c; called blind from src/game/bg.c */
void *memaAlloc(u32 amount);
/* src/memp.c; called blind from src/game/stan.c */
const char *tokenFind(s32 arg0, const char *arg1);

#endif
